### ISSUE TITLE
8月9日新版，上传加速的问题

### ISSUE THREAD

**Issue by linran125** [fffonion/Xunlei-Fastdick#101]
通过命令`python ./swjsq.py`前台运行没有问题，但是用后台运行模式上传加速非常不稳定，时有时无，下传加速没问题

**Comment by fffonion** [comment]
什么是后台运行模式？

**Comment by pingshu** [comment]
通过命令python ./swjsq.py运行上行只能提速10分钟左右，加入自动启动好像不工作

**Comment by linran125** [comment]
就是用您的教程里写的nohup，还有'python ./swjsq.py &'。nohup那条根本就不起作用，后面这条就是出现我说的不稳定问题。用'python ./swjsq.py'前台运行时很稳定，但是不能关Xshell窗口啊。

**Comment by fffonion** [comment]
ok我一会更新

**Comment by linran125** [comment]
今天的更新也试了，上传效果还是不稳定，就像开车时的油门，踩几秒，松几秒，踩几秒，松几秒，一直这么循环

**Comment by pingshu** [comment]
我的swjsq.py是放在/data/usr/bin/swjsq文件夹里，你的说明里写的“nohup python /data/usr/bin/swjsq.py >/dev/null 2>&1 &”  路径对吗

**Comment by pingshu** [comment]
安装了ipk包才好

**Comment by fffonion** [comment]
@pingshu 说明有误，应该是`SSH进入目录/data/usr/bin/`
