### ISSUE TITLE
PandoraBox使用shell脚本时报错（通过ipk安装）

### ISSUE THREAD

**Issue by fanck0605** [fffonion/Xunlei-Fastdick#103]
PandoraBox设置了开机自动启动，并在开机后多次手动尝试重启swjsq均无果，在电脑上用py脚本正常

# **错误日志（直接在ssh中运行swjsq）：**
/bin/swjsq: line 47: function: not found
16:57:57
/bin/swjsq: line 49: syntax error: unexpected "}"

# **47-49行内容：**
![16](https://user-images.githubusercontent.com/28819315/29248412-50e09ddc-804a-11e7-8adf-136e48e88d7d.png)

# **系统日志：**
Sun Aug 13 16:47:18 2017 user.err detect_internet[2285]: get interfaces ipaddr failed!
Sun Aug 13 16:47:18 2017 daemon.info detect_internet[2285]: get interfaces ipaddr failed!
Sun Aug 13 16:47:20 2017 daemon.err swjsq[2286]: Segmentation fault
Sun Aug 13 16:47:20 2017 daemon.err swjsq[2286]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:47:20 2017 daemon.info swjsq[2286]: 16:47:20
Sun Aug 13 16:47:20 2017 daemon.err swjsq[2286]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:47:23 2017 user.err detect_internet[2338]: get interfaces ipaddr failed!
Sun Aug 13 16:47:23 2017 daemon.info detect_internet[2338]: get interfaces ipaddr failed!
Sun Aug 13 16:47:26 2017 daemon.err swjsq[2474]: Segmentation fault
Sun Aug 13 16:47:26 2017 daemon.err swjsq[2474]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:47:26 2017 daemon.info swjsq[2474]: 16:47:26
Sun Aug 13 16:47:26 2017 daemon.err swjsq[2474]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:47:28 2017 user.err detect_internet[2496]: get interfaces ipaddr failed!
Sun Aug 13 16:47:28 2017 daemon.info detect_internet[2496]: get interfaces ipaddr failed!
Sun Aug 13 16:47:31 2017 daemon.err swjsq[2541]: Segmentation fault
Sun Aug 13 16:47:31 2017 daemon.err swjsq[2541]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:47:31 2017 daemon.info swjsq[2541]: 16:47:31
Sun Aug 13 16:47:31 2017 daemon.err swjsq[2541]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:47:33 2017 user.err detect_internet[2551]: get interfaces ipaddr failed!
Sun Aug 13 16:47:33 2017 daemon.info detect_internet[2551]: get interfaces ipaddr failed!
Sun Aug 13 16:47:33 2017 daemon.info procd: Instance detect_internet::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sun Aug 13 16:47:36 2017 daemon.err swjsq[2552]: Segmentation fault
Sun Aug 13 16:47:37 2017 daemon.err swjsq[2552]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:47:37 2017 daemon.info swjsq[2552]: 16:47:37
Sun Aug 13 16:47:37 2017 daemon.info procd: Instance swjsq::instance1 s in a crash loop 6 crashes, 1 seconds since last crash
Sun Aug 13 16:47:37 2017 daemon.err swjsq[2552]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:48:38 2017 daemon.err swjsq[3042]: Segmentation fault
Sun Aug 13 16:48:39 2017 daemon.err swjsq[3042]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:48:39 2017 daemon.info swjsq[3042]: 16:48:39
Sun Aug 13 16:48:39 2017 daemon.err swjsq[3042]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:48:44 2017 daemon.err swjsq[3086]: Segmentation fault
Sun Aug 13 16:48:44 2017 daemon.err swjsq[3086]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:48:44 2017 daemon.info swjsq[3086]: 16:48:44
Sun Aug 13 16:48:44 2017 daemon.err swjsq[3086]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:48:49 2017 daemon.err swjsq[3097]: Segmentation fault
Sun Aug 13 16:48:49 2017 daemon.err swjsq[3097]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:48:49 2017 daemon.info swjsq[3097]: 16:48:49
Sun Aug 13 16:48:49 2017 daemon.err swjsq[3097]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:48:55 2017 daemon.err swjsq[3107]: Segmentation fault
Sun Aug 13 16:48:55 2017 daemon.err swjsq[3107]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:48:55 2017 daemon.info swjsq[3107]: 16:48:55
Sun Aug 13 16:48:55 2017 daemon.err swjsq[3107]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:49:00 2017 daemon.err swjsq[3124]: Segmentation fault
Sun Aug 13 16:49:00 2017 daemon.err swjsq[3124]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:49:00 2017 daemon.info swjsq[3124]: 16:49:00
Sun Aug 13 16:49:00 2017 daemon.err swjsq[3124]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:49:05 2017 daemon.err swjsq[3134]: Segmentation fault
Sun Aug 13 16:49:06 2017 daemon.err swjsq[3134]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:49:06 2017 daemon.info swjsq[3134]: 16:49:06
Sun Aug 13 16:49:06 2017 daemon.err swjsq[3134]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:49:06 2017 daemon.info procd: Instance swjsq::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sun Aug 13 16:50:44 2017 authpriv.info dropbear[3145]: Child connection from 192.168.1.100:54747
Sun Aug 13 16:50:49 2017 authpriv.notice dropbear[3145]: Password auth succeeded for 'root' from 192.168.1.100:54747
Sun Aug 13 16:51:14 2017 daemon.err swjsq[3162]: Segmentation fault
Sun Aug 13 16:51:15 2017 daemon.err swjsq[3162]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:51:15 2017 daemon.info swjsq[3162]: 16:51:15
Sun Aug 13 16:51:15 2017 daemon.err swjsq[3162]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:51:20 2017 daemon.err swjsq[3206]: Segmentation fault
Sun Aug 13 16:51:20 2017 daemon.err swjsq[3206]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:51:20 2017 daemon.info swjsq[3206]: 16:51:20
Sun Aug 13 16:51:20 2017 daemon.err swjsq[3206]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:51:25 2017 daemon.err swjsq[3216]: Segmentation fault
Sun Aug 13 16:51:25 2017 daemon.err swjsq[3216]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:51:25 2017 daemon.info swjsq[3216]: 16:51:25
Sun Aug 13 16:51:25 2017 daemon.err swjsq[3216]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:51:31 2017 daemon.err swjsq[3258]: Segmentation fault
Sun Aug 13 16:51:31 2017 daemon.err swjsq[3258]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:51:31 2017 daemon.info swjsq[3258]: 16:51:31
Sun Aug 13 16:51:31 2017 daemon.err swjsq[3258]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:51:36 2017 daemon.err swjsq[3268]: Segmentation fault
Sun Aug 13 16:51:36 2017 daemon.err swjsq[3268]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:51:36 2017 daemon.info swjsq[3268]: 16:51:36
Sun Aug 13 16:51:36 2017 daemon.err swjsq[3268]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:51:41 2017 daemon.err swjsq[3278]: Segmentation fault
Sun Aug 13 16:51:42 2017 daemon.err swjsq[3278]: /bin/swjsq: line 47: function: not found
Sun Aug 13 16:51:42 2017 daemon.info swjsq[3278]: 16:51:42
Sun Aug 13 16:51:42 2017 daemon.err swjsq[3278]: /bin/swjsq: line 49: syntax error: unexpected "}"
Sun Aug 13 16:51:42 2017 daemon.info procd: Instance swjsq::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

# **附上在PandoraBox路由上使用py脚本的报错：**
Warning: pycrypto not found, use pure-python implemention
17:59:57 Login xunlei succeeded
17:59:57 Expire date for fastdick: 20180722
Traceback (most recent call last):
  File "./swjsq.py", line 790, in <module>
    ins.run(uid, hashlib.md5(pwd).hexdigest())
  File "./swjsq.py", line 425, in run
    'To Upgrade: %s %s %s' % ( _avail['province'], _avail['sp'], ", ".join(_to_upgrade))
  File "./swjsq.py", line 198, in uprint
    print(s.encode('utf-8'), end = end)
  File "./swjsq.py", line 179, in print
    logfd.write(line.encode('utf-8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 21: ordinal not in range(128)

**Comment by fffonion** [comment]
后一个py的问题并入 #102

**Comment by fanck0605** [comment]
使用新版问题解决

**Comment by fffonion** [comment]
我傻了
![ee1243789164705281839ca7046796c8](https://user-images.githubusercontent.com/2135445/29279902-538852b2-80e7-11e7-85d5-6b6c01d46871.gif)
