### ISSUE TITLE
迅雷超级会员运行时提示既不是快鸟会员也不是上行加速会员，买买买！

### ISSUE THREAD

**Issue by cricketbrother** [fffonion/Xunlei-Fastdick#104]
newifi D1 + Padavan 8月6日版本
运行后提示：
[RT-N56U_B1 /opt/FastDick]# python /opt/FastDick/swjsq.py                                                                                                                                                          
13:46:20 Warning: get interface_ip failed, use fallback address
13:46:21 Login xunlei succeeded
13:46:23 Error: You are neither xunlei fastdick member nor upstream acceleration member, buy buy buy!
Debug: [{u'other_vasType': 0, u'other_isVip': 0, u'other_payName': u'----', u'other_vipGrow': 0, u'other_vipDayGrow': 0, u'other_isRemind': 0, u'other_vipLevel': 0, u'other_isAutoDeduct': 0, u'other_expireDate':
 u'----', u'other_payId': 0}, {u'other_vasType': 0, u'other_isVip': 0, u'other_payName': u'----', u'other_vipGrow': 0, u'other_vipDayGrow': 0, u'other_isRemind': 0, u'other_vipLevel': 0, u'other_isAutoDeduct': 0
, u'other_expireDate': u'----', u'other_payId': 0}]
超级会员是有权限使用快鸟的，在手机端和PC端都可以正常加速成功。之前用这个脚本成功使用过，最近突然就不行了。

2017-8-17更新：今天尝试使用了一下8个月前的老版本，可以正常启动，我是北京联通

**Comment by sh3rry** [comment]
我也是同样的报错，大约5天前出现的问题，超级会员11月到期，pc端正常加速。

**Comment by fffonion** [comment]
- [X] 已经增加超级会员的判断

（开了一个月的超级会员![ldib0h kie d_mp49 q4gx](https://user-images.githubusercontent.com/2135445/29536040-49d421da-868a-11e7-8bc9-ba99e0d31927.jpg)

**Comment by sh3rry** [comment]
thx！ 测试中，明天反馈。

**Comment by sh3rry** [comment]
![apnukrcc2bn jds95ovu pe](https://user-images.githubusercontent.com/9400373/29536791-d1f48fca-86f1-11e7-96ab-057fa23db35f.png)
仍有报错，参考 https://github.com/timothyqiu/python-swjsq/issues/2 ，虽然不能显示出带宽，但是直接提速仍可以成功。

**Comment by fffonion** [comment]
@sh3rry UnicodeDecodeError的问题#102正在修复中

**Comment by sh3rry** [comment]
@fffonion 中间还有"can not upgrade"的错误，可能是没有获取到可提速的带宽?

**Comment by fffonion** [comment]
@sh3rry 这个can_upgrade是快鸟的api返回的结果，应该和app或者pc客户端里显示的一样，可能是上行或者下行无法提速。可以先把179行删掉

**Comment by sh3rry** [comment]
![2 6o6 ktcux17s fhu c n](https://user-images.githubusercontent.com/9400373/29537374-10bb0a48-86f4-11e7-842b-e3cb38b6cf4d.png)
正常了，谢谢。

**Comment by fffonion** [comment]
👌

**Comment by cricketbrother** [comment]
感谢作者，最新版本已可以正常使用
