### ISSUE TITLE
贝尔G-120W-B天翼网关，即电信光猫可否运行本项目？

### ISSUE THREAD

**Issue by linux0ne** [fffonion/Xunlei-Fastdick#109]
我的操作系统 ：win10 64
我的宽带运营商：中国电信，我在黑龙江地区，100M光纤，快鸟支持。
电信赠送了一个光猫，即贝尔G-120W-B天翼网关，这货的超级管理员我已破解，但只能做一些管理参数的调整，写入不了任何内容到光猫中去。

注：这款光猫自带wifi功能，自带PPPOE功能，竟然还支持桥接模式，以便关闭PPPOE后挂上某路由去拨号……

不知道这个问题是否适合在此提出，还请包含，只想在技术层面上讨论一下。

**Comment by fffonion** [comment]
如果能使用ssh或者telnet，并且能使用busybox，那就可以用。
写入不了可以考虑每次开机时下载到/tmp或者类似的临时文件系统里。

**Comment by linux0ne** [comment]
@fffonion 我在win10下可以用telnet，但是不知道能不能用busybox，这个我需要尝试，有结果再回复。谢谢。

注：busybox的意思就是要把这套组件安装到光猫上去是吧？

**Comment by fffonion** [comment]
没有的话你也可以开机的时候下一个到临时文件系统里

**Comment by linux0ne** [comment]
@fffonion 
可否再教我一下如何在/tmp目录下下载busybox呢？

我现在已经telnet到了光猫儿的/tmp目录下了，而且是超级用户权限。

因为这涉及到下载哪个版本的busybox   还涉及到如何安装、编译   

谢谢。

**Comment by fffonion** [comment]
这个我建议还是到专门的论坛里问一下吧，我也不太清楚。
你可以根据cpu架构和c库来去网上找一个别人编译好的busybox。
这个issue我就先关了: )

**Comment by l0g1n** [comment]
我也是这一款，直接修改config.xml是修改不了的。我研究了一晚上，找到了办法。程序里面自带了一个命令行工具：cfgcli。可以用来获取，设置参数。如获取参数cfgcli -g InternetGatewayDevice.Services.X_CT-COM_MWBAND.TotalTerminalNumber（这是光猫可连接的终端个数，默认是7）。设置操作如下：cfgcli -s InternetGatewayDevice.Services.X_CT-COM_MWBAND.TotalTerminalNumber 99。禁用各种限制：cfgcli -s InternetGatewayDevice.Services.X_CT-COM_MWBAND.Mode 0。
