### ISSUE TITLE
关于api_url查询的一个逻辑小问题

### ISSUE THREAD

**Issue by oscar-c** [fffonion/Xunlei-FastDick#11]
发现了一个bug。
在生成的`swjsq_wget`的脚本里面， `api_url="http://$portal_ip:$portal_port/v2"`这一行应该放在紧接下来的 `if [ -z "$portal_ip" ]` 那个 block 的后面。
你放在了这个block的前面，导致第一次查询失败之后，就算等了30秒再查询，查询出了正确的结果，也不能写入`$api_url`里面

**Comment by ninggu2008** [comment]
我的锅，当时想增加代码处理下查不到ip的情况，但是没机会测试，所以。

**Comment by oscar-c** [comment]
我的环境就是第一次运行的时候获取不到IP地址，所以发现了这个问题。
