### ISSUE TITLE
协议改了还是服务器换了最近维护后都无法加速

### ISSUE THREAD

**Issue by caiy92** [fffonion/Xunlei-Fastdick#111]
E:\xl>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
20:46:24 Warning: get interface_ip failed, use fallback address
20:46:25 Login xunlei succeeded
20:46:25 Expire date for chaoji member: 20180805
20:46:26 Warning: error during downapi connection: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>, use portal: 119.147.41.210:12180
20:46:26 Error: can't connect to down api
生成的脚本也提示119那个服务拒绝连接

**Comment by derekhe** [comment]
+1

**Comment by fffonion** [comment]
试试这几个url能不能返回portal_ip?
http://api.portal.swjsq.vip.xunlei.com:81/v2/queryportal
http://api.portal.swjsq.vip.xunlei.com:82/v2/queryportal
http://api2.portal.swjsq.vip.xunlei.com:81/v2/queryportal
另外`FALLBACK_PORTAL`我这可以连上，可以尝试浏览器打开
http://119.147.41.210:12180/v2/bandwidth

**Comment by caiy92** [comment]
间歇性无法连接，浏览器打开{"errno":502,"message":"channel error:parameter error","richmessage":"","sequence":0,"timestamp":1507893227}
暂时能用了，

**Comment by fffonion** [comment]
@caiy92 emmm可能是迅雷昨天抽风了

**Comment by Daopr** [comment]
我发现现在无效啊，windows 10的快鸟才可以用。先在群晖里跑了 docker，没有效果，然后开 xp 的迅雷快鸟也没效果，然后打开 windows 10的快鸟，然后提示要开个网页才激活。然后开了网页，网速就飚上去了。

**Comment by Daopr** [comment]
是不是现在还有个激活的流程没走啊？

**Comment by Daopr** [comment]
我对抓包不是很在行，但是应该是有个几分钟的心跳在维持 加速过后的 激活状态

**Comment by fffonion** [comment]
@Daopr 请准确地描述一下问题
参考https://github.com/fffonion/Xunlei-Fastdick/blob/master/CONTRIBUTING.md

**Comment by Daopr** [comment]
问题就是,
1.我运行了 swjsq,显示提速成功,
  结果就是速度没有提到100m, 
2.当我又打开了 windows10上的迅雷加速或者是梅林上的迅雷插件,
速度才提上去.

**Comment by fffonion** [comment]
@Daopr 显示提速成功速度没有提升的话，目前来看是迅雷或者运营商那里的问题

**Comment by fffonion** [comment]
关闭未活跃issue，如有需要请重新打开：）
