### ISSUE TITLE
求助迅雷快鸟安装出错，电脑运行py脚本错误

### ISSUE THREAD

**Issue by qc1120525176** [fffonion/Xunlei-Fastdick#112]
创建了swjq.ccount.txt,但是好像提示找不到文件

**Comment by fffonion** [comment]
是不是没有显示扩展名？
https://jingyan.baidu.com/article/fea4511a5ea60cf7ba912550.html

**Comment by qc1120525176** [comment]
我现在是用家里的广电宽带来设置，打算设置好再放到有电信宽带的地方，这样方法可行吗

**Comment by qc1120525176** [comment]
这个问题我有拍照，但是这里好像发不了图片，能有联系方式吗

**Comment by fffonion** [comment]
如果你要生成shell脚本给路由器用的话，必须得加速成功之后才会生成.sh和.ipk，所以只能在有电信的地方用。如果只用python版，那无所谓。

你可以去这里上传图片 https://img.yooooo.us/

**Comment by qc1120525176** [comment]
只用Python版是什么意思，在路由器安装Python吗

**Comment by fffonion** [comment]
对，或者在pc上开python也行233

**Comment by qc1120525176** [comment]
我上传图片了，大神帮我看下

**Comment by fffonion** [comment]
那你就是没建对**swjsq.account.txt**，或者没有显示扩展名，导致建的文件后面多了个`.txt`，可以参考2楼的链接

**Comment by qc1120525176** [comment]
我的路由器固件有集成Python了

**Comment by qc1120525176** [comment]
哦，我中午试一下

**Comment by qc1120525176** [comment]
现在意味着我只能用路由Python那个方法，因为有电信宽带的地方没有电脑，所以生成不了那个ipk，对吗

**Comment by fffonion** [comment]
在路由器上用python的那个方法，也可以生成ipk

**Comment by qc1120525176** [comment]
又放三张图，有空帮我看下

**Comment by fffonion** [comment]
```
cd /usr/bin
python ./swjsq.py
```
类似问题请自己百度：）
