### ISSUE TITLE
Xunlei-FastD1ck cannot find wget or curl installed with https(ssl) enabled in this system.

### ISSUE THREAD

**Issue by imshell8** [fffonion/Xunlei-Fastdick#114]
opkg update之后opkg install wget也还是一样的提示，已经给了777权限，重启等方法也试过，不行。重新生成一次还是遇见相同的问题

**Comment by imshell8** [comment]
问题已经解决。
1、opkg update
2、opkg install wget
3、opkg install curl

希望有遇见相同问题的朋友们能够快速知晓问题快速解决。

**Comment by fffonion** [comment]
1.在路由器上安装支持https的wget或curl

安装了wget之后仍然报错是因为这个wget不带https支持
如果安装curl则不需要再安装wget 😃
