### ISSUE TITLE
协议估计是换了...大规模无法提速~~~

### ISSUE THREAD

**Issue by lonlykids** [fffonion/Xunlei-Fastdick#115]
00:20:05 Error: login xunlei failed, 协议不合法，请联系客服确认！
00:20:05 {u'isequenceNo': 1000001, u'errorCode': 12, u'cmdID': 2, u'errorDesc': u'\u534f\u8bae\u4e0d\u5408\u6cd5\uff0c\u8bf7\u8054\u7cfb\u5ba2\u670d\u786e\u8ba4\uff01', u'protocolVersion': 108, u'platformVersion': 1, u'errorIsRetry': 0, u'sCompressed': 0, u'errorDescUrl': u''}
这个是Log...
网页提速Ok...App提速Ok...试用提速Ok...

**Comment by fffonion** [comment]
网页提速是啥，能给个链接不

**Comment by hhyzz** [comment]
[http://k.xunlei.com/tisu.html](url) @fffonion
