### ISSUE TITLE
协议不合法？

### ISSUE THREAD

**Issue by shanes128** [fffonion/Xunlei-Fastdick#119]
Warning: pycrypto not found, use pure-python implemention
20:53:15 Error: login xunlei failed, 协议不合法，请联系客服确认！
20:53:15 {'platformVersion': 1, 'errorCode': 12, 'errorDescUrl': '', 'errorDesc': '协议不合法，请联系客服确认！', 'cmdID': 2, 'protocolVersion': 108, 'errorIsRetry': 0, 'sCompressed': 0, 'isequenceNo': 1000001}

**Comment by fffonion** [comment]
合并 #97
