### ISSUE TITLE
小米版失效

### ISSUE THREAD

**Issue by NIGHT-CORE** [fffonion/Xunlei-Fastdick#12]
今天发现小米版ipk失效，以下是 py模式下的的错误的代码
Login xunlei succeeded
To Upgrade: ***   Down 20M -> 30M, Up 2M -> 100M
Initializing upgrade
Error: channel error:tel_proxy timeout
付：maste版正常

**Comment by fffonion** [comment]
应该不是脚本的问题
我猜是
客户端 <====> 快鸟api <=xx=> 运营商接口
↑这样了

**Comment by ninggu2008** [comment]
我这里正常啊。可能是各地网络环境不同导致的吧。

**Comment by NIGHT-CORE** [comment]
no idea ，阶段性失灵，master一直可以……
