### ISSUE TITLE
迅雷快鸟脚本加速失败

### ISSUE THREAD

**Issue by imshell8** [fffonion/Xunlei-Fastdick#120]
地址：福建电信
错误日志：
17:56:09 Error: login xunlei failed, 您的帐号存在异常,请登录安全中心确认！
17:56:09 {u'isequenceNo': 1000001, u'errorCode': 6, u'cmdID': 2, u'errorDesc': u'

还有一条是
协议不合法，

改过密码，也重启过光猫，跟客服人员反馈过，客服人员说更改密码后2个小时后重启一下光猫，照做了，第二次询问也是一样的操作方法，我就隔了24小时之后重启的

现在的错误是 您的账号存在异常，麻烦作者看一下是不是协议的问题还是？已经5天过去了，电脑端可以加速，没有任何验证码提示

**Comment by Lonlykids** [comment]
#97 可以去这里看.目前不单止协议换了..连登陆入口都换了...目前开发卡在无人脱壳

**Comment by fffonion** [comment]
@imshell8 请关注#97，这个issue我关掉了
