### ISSUE TITLE
建议更改验证https的地址从https://baidu.com为https://cn.bing.com

### ISSUE THREAD

**Issue by liuem** [fffonion/Xunlei-Fastdick#128]
我使用**WNDR4300 V1**
刷入 **LuCI lede-17.01** branch (git-17.290.79498-d3f0685) 后，
使用电脑**python3.6生成的.sh脚本**文件，导入到路由器执行后不能正常通过，
提示"Xunlei-FastD1ck **cannot find wget or curl** installed with https(ssl) enabled in this system."。

经过检查，weget访问百度的时候，不能正常连接，一直在等待数据。换成bing后可以正常返回。这可能是百度不允许忽略证书。
我改成
https://cn.bing.com后，成功运行，加速成功

**Comment by viqbgrg** [comment]
真巧,我昨天wget baidu,com的时候我的路由器不知道为啥,会乱码,然后也换成了bing的网址发现可以了,不会乱码了

**Comment by fffonion** [comment]
有道理，我改成baidu和bing都失败才报错好了

**Comment by fffonion** [comment]
因为大多数用户没有反应这个问题，暂时不改了
如果仍有问题请重新打开issue

**Comment by bincat233** [comment]
我也遇到了同样的问题
环境是 asuswrt-merlin 386.1 (原版), 已安装 antware.

最后我也改成bing的网址了
