### ISSUE TITLE
提示输入验证码

### ISSUE THREAD

**Issue by 516018579** [fffonion/Xunlei-Fastdick#129]
运行脚本  错误信息:login xunlei failed, 为了您的账号安全，请输入验证码

**Comment by sensec** [comment]
去改一下密码再启动

**Comment by 516018579** [comment]
我改了密码没效果,然后随便填了账号密码还是同样的错误
然后把swjsq.account.txt文件删除后运行一次,提示找不到文件后,再重新新建了swjsq.account.txt运行就好了。

**Comment by fffonion** [comment]
@516018579 可能是loginkey太久了长毛了，我去改一下

**Comment by fhxu** [comment]
swjsq.account.txt 这个文件在哪里可以删除，我群晖上也出现了这个问题，望指教一下。感谢！

**Comment by fffonion** [comment]
@fhxu 这个文件登陆成功之后就删除了，直接在swjsq.py同目录下新建一个即可

**Comment by fhxu** [comment]
@fffonion 
![qq 20180404084230](https://user-images.githubusercontent.com/1622845/38282732-4f872a9e-37e4-11e8-99ae-e8a1c013e888.png)
更改密码后，又是这个错误提示。
还有不知道群晖的Docker文件在哪里

**Comment by fffonion** [comment]
如有问题请重新打开issue : )
