### ISSUE TITLE
双wan口如何设置（只有其中一条wan口支持快鸟加速）

### ISSUE THREAD

**Issue by cheeseyang** [fffonion/Xunlei-FastDick#13]

**Comment by fffonion** [comment]
如果两个wan都能连外网的话，可以设置防火墙让112.80.23.136，112.80.23.135（api.portal.swjsq.vip.xunlei.com）的出站包发往需要加速的wan对应的网卡。建议浏览器请求一下`http://api.portal.swjsq.vip.xunlei.com:81/v2/queryportal`，把里面出现的ip地址也填到这个规则里去。
如果只有一条能连外网的话，直接用就行了

**Comment by cheeseyang** [comment]
谢谢热心回复，搞定了

**Comment by heeroyuyj** [comment]
@fffonion

单线双拨, 用两个快鸟账号, 可以实现每个 WAN 单独走加速吗?

**Comment by fffonion** [comment]
@heeroyuyj 我不太清楚运营商具体怎么控制加速，不好下结论。
你可以试一下，需要配一下防火墙

**Comment by river1** [comment]
双拨具体要怎么设置防火墙，谁能来科普一下？

**Comment by fffonion** [comment]
哦我突然想到了如果用curl的话可以用
`curl --interface 网卡名` 来指定使用的ip

**Comment by river1** [comment]
现在总算试出来了，单线双拨只能加速一条线路，用第二个快鸟账号通过另外一个ip连接时会提示此宽带已加速，加速的只有先连接的那条线路

**Comment by just4somefun** [comment]
看来是根据宽带账号来判断是否能加速/已加速的，单线多拨指定出口后只能单线加速
