### ISSUE TITLE
您好，请问提示Invalid syntax怎么处理

### ISSUE THREAD

**Issue by MEZboy** [fffonion/Xunlei-Fastdick#130]
我使用电脑或者路由器或者群晖，都是提示这个，是哪里出了问题呢

![tim 20180314095019](https://user-images.githubusercontent.com/5998050/37379175-51cff3ee-276d-11e8-9ff4-e3f238506fd1.png)

**Comment by fffonion** [comment]
你下载的python脚本有问题，可以右键另存为这个链接：
https://github.com/fffonion/Xunlei-Fastdick/raw/master/swjsq.py

**Comment by MEZboy** [comment]
搞定，感谢！
