### ISSUE TITLE
上行不能加速成功

### ISSUE THREAD

**Issue by henjue** [fffonion/Xunlei-Fastdick#131]
上海电信
群晖运行最新docker版本
http://netreport.sh.189.cn/speed/main.html 
这里测试下行没问题，上行无效。
log输出正常
![1](https://user-images.githubusercontent.com/1314740/37901574-32534e74-3124-11e8-81ea-4a58a1e1caed.png)

**Comment by fffonion** [comment]
另见#132 超级会员没有上行特权，已在 b25b84f 中修复

**Comment by henjue** [comment]
@fffonion 我开通了一年的上行提速会员了

**Comment by henjue** [comment]
@fffonion 我刚测试生效了，估计是迅雷的问题

**Comment by fffonion** [comment]
@henjue 你是同时开了超级会员和上行会员吗？
那现在的判断应该有问题，我明天再改一下

**Comment by henjue** [comment]
@fffonion 是的我一直同时开了超级会员和上行会员。
