### ISSUE TITLE
响应为gzip格式时报错UnicodeDecodeError

### ISSUE THREAD

**Issue by zhoujianjoe** [fffonion/Xunlei-Fastdick#136]
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in po
报这个错误 还有就是迅雷客服说登录频率过高 现在限制登录了 能改下频率吗

**Comment by irol765** [comment]
把swjsq.py里面的gzip都删掉就好了。

**Comment by zhoujianjoe** [comment]
我是群晖的docker 看不到实际的脚本文件啊，在哪儿改啊

**Comment by irol765** [comment]
我也是群晖，我是这样解决的：
1、在docker文件夹下新建fastdick
2、下载swjsq.py，修改后放入
3、编辑docker容器，选择映射卷，将此文件映射到/swjsq.py，并只读，保存容器。
4、启动容器

**Comment by zhoujianjoe** [comment]
OK 我来试试 感谢

**Comment by zhoujianjoe** [comment]
搞定了 感谢irol765的协助

**Comment by fffonion** [comment]
已在 1d5306d 中修复
