### ISSUE TITLE
单独的上行会员无法加速上行

### ISSUE THREAD

**Issue by jzz567** [fffonion/Xunlei-Fastdick#138]
谢谢你们脚本！让我路由器一开机的时候就能加速。
但是最新的那个脚本好像有点问题。。
我是超级会员，然后单独购买了上行提速，但py脚本不加速上行。。。以前用的都挺好的。。
貌似脚本没有尝试上行加速？
![default](https://user-images.githubusercontent.com/15991754/38728809-8526b3f2-3f43-11e8-9ef0-0174cbbdfd5f.png)

![default](https://user-images.githubusercontent.com/15991754/38728644-0750c378-3f43-11e8-9e6c-f2ea12fbb22b.png)

**Comment by fffonion** [comment]
感谢报告，已更新：）

**Comment by jzz567** [comment]
@fffonion 使用了新脚本后已经解决，谢谢!
