### ISSUE TITLE
迅雷登录成功 但是上行提速失败

### ISSUE THREAD

**Issue by GaryQK** [fffonion/Xunlei-Fastdick#139]
![image](https://user-images.githubusercontent.com/5860015/39366662-20032ecc-4a67-11e8-851d-56bf53a0e966.png)

**Comment by GaryQK** [comment]
找到原因了 ，返回的 dial_account 字段 宽带账号 信息 获取失败 获取的是 空字符串

**Comment by fffonion** [comment]
嗯，前面有warning显示“电信线路暂不支持”了。因为有用户反映会误判，所以在迅雷返回无法加速时仍然会尝试加速。

**Comment by GaryQK** [comment]
我直接把我的宽带账号 赋给了变量 就可以使用了 也不纠结了 暂时就这样吧 。。=。=！
