### ISSUE TITLE
感谢分享，特别好用，咨询一点菜鸟问题

### ISSUE THREAD

**Issue by mickeybricks** [fffonion/Xunlei-FastDick#14]
您好，我用了您的这个swjsq.py确实好用，也安装在了路由里面（wndr3800，openwrt）。
问题是：
1.可能我的openwrt系统不稳定，这个程序不是一直处于运行状态，经常过一夜就不再提速。这就带来了问题2
2.我现在启动swjsq的方式都是使用windows下的putty或者mac os下的终端，想咨询一下在openwrt的LuCI界面里有没有直接启动程序的方法呢？
万望赐教，不胜感激TAT

**Comment by fffonion** [comment]
启动的时候最后加了&嘛？
另外如果是用的python，有可能会因为内存不够用被干掉，可以试试wget.sh
目前没有luci模块来启动脚本:)

**Comment by zhoujianqing** [comment]
特别感谢您分享！我是一个十足的新手，现在能
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: 江苏电信 Down 20M -> 50M, Up 4M -> 100M
Initializing upgrade
Upgrade done: Down 50M, Up 4096M，
但是接下来把swjsq_0.0.1_all.ipk，swjsq_wget.sh放到/tmp发现不会怎么安装ipk，您这里没讲，我网上找了半天也不会，可能缺的知识比较多，请问能详细的指导下我吗？感谢！

**Comment by fffonion** [comment]
opkg install swjsq_0.0.1_all.ipk就可以
或者可以直接把swjsq_wget.sh拷到/tmp，然后
chmod +x ./swjsq_wget.sh
./swjsq_wget.sh &
关掉后台：
killall swjsq

**Comment by zhoujianqing** [comment]
����./swjsq_wget.sh &
����not found
�������� iPad

> �� 2015��10��2��������2:43��Alliumcepa Triplef <notifications@github.com> ������
> 
> ./swjsq_wget.sh &

**Comment by fffonion** [comment]
@zhoujianqing 乱码了

**Comment by zhoujianqing** [comment]
我直接ipad端回复邮件，居然乱码了

**Comment by zhoujianqing** [comment]
试了opkg install ...命令，发现卡住不动了，按回车也没反应

**Comment by fffonion** [comment]
这我就不知道了
![xgm bs _gbfif _th9k 1jv](https://cloud.githubusercontent.com/assets/2135445/10251474/f451f41c-68fe-11e5-8009-ee90b37c6926.jpg)

**Comment by zhoujianqing** [comment]
再试一次就变成opkg_conf_load:could not lock /var/lock/opkg.lock:resource temporarily unavailable

**Comment by zhoujianqing** [comment]
我是小米路由器，帮帮忙啊，我很需要您的这个成果，网速能提升50%

**Comment by fffonion** [comment]
@zhoujiangqing 我感觉是你opkg用的不太对
swjsq_wget.sh要拷到路由器里才行

**Comment by shenwei356** [comment]
大家好，知道这是什么原因么？

```
Login xunlei succeeded
To Upgrade: chong_qing tel Down 4M -> 50M, Up 0M -> 50M
Initializing upgrade
Error: speedup server already speed up
```

不知是否开了PC端的快鸟

**Comment by fffonion** [comment]
@shenwei356 这样没关系的
如果比较强迫症可以按ctrl+c退出一次，再运行脚本 ctrl+c退出的时候会恢复到原速

**Comment by mickeybricks** [comment]
@zhoujianqing 1. 你是小米路由不是在官网上有直接下载的包吗？不需要这么麻烦。
2. http://www.right.com.cn/forum/thread-170502-1-1.html你可以按这个步骤做，我就是这样弄的。

**Comment by mickeybricks** [comment]
@fffonion 加了&符号之后可以持续运行好久，差不多每天登陆一次就行了，方便多了，多谢哈^^
能给科普一下命令后面加&什么意思吗？多谢

**Comment by fffonion** [comment]
@mickeybricks &就是放到后台的意思
