### ISSUE TITLE
已开通迅雷上行会员，登录成功却提示没有开通会员

### ISSUE THREAD

**Issue by ta1994** [fffonion/Xunlei-Fastdick#140]
系统：LEDE/openwrt17.01
swjsq.log文件为空

以下为运行后提示
11:31:54 Login xunlei succeeded
11:31:54 Error: You are neither xunlei fastdick member nor upstream acceleration                                         member, buy buy buy!
Debug: [{u'expireDate': u'----', u'payId': u'0', u'isRemind': u'0', u'isYear': u                                        '0', u'isAutoDeduct': u'0', u'vipLevel': u'0', u'payName': u'----', u'vasid': u'                                        14', u'isVip': u'0', u'vasType': u'0', u'vipDayGrow': u'0', u'vipGrow': u'0'}]

**Comment by fffonion** [comment]
这个`u'expireDate': u'----'`是你去掉的还是本来就这样？

**Comment by ta1994** [comment]
不不不，我没有做任何修改。这是ssh运行后的提示

**Comment by ocean19** [comment]
前置条件： 只开通上行提速， 不开通会员
系统：win7
运行命令：python swjsq.py
运行输出如下：
12:21:46 Login xunlei succeeded
12:21:46 Error: You are neither xunlei fastdick member nor upstream acceleration
 member, buy buy buy!
Debug: [{u'expireDate': u'20180528', u'payId': u'617', u'isRemind': u'0', u'isYe
ar': u'0', u'isAutoDeduct': u'0', u'vipLevel': u'1', u'payName': u'\u6dd8\u5b9d\
u76f4\u5145', u'vasid': u'14', u'isVip': u'0', u'vasType': u'3', u'vipDayGrow':
u'12', u'vipGrow': u'0'}]

20180528以前我既开通了快鸟会员， 又开通了上行提速会员， 20180528以后我只开通了迅雷上行提速会员，使用迅雷WINDOWS客户端登陆，上行提速成功。   使用脚本却提示出错， 请帮忙解决下， 谢谢！

**Comment by fffonion** [comment]
已更新，请尝试新版：）

**Comment by fffonion** [comment]
默认解决，关闭老帖：）
