### ISSUE TITLE
只开通快鸟上行提速会员，不开通快鸟会员，运行报错！

### ISSUE THREAD

**Issue by ocean19** [fffonion/Xunlei-Fastdick#142]
前置条件： 只开通上行提速， 不开通会员
系统：win7
运行命令：python swjsq.py
运行输出如下：
12:21:46 Login xunlei succeeded
12:21:46 Error: You are neither xunlei fastdick member nor upstream acceleration
 member, buy buy buy!
Debug: [{u'expireDate': u'20180528', u'payId': u'617', u'isRemind': u'0', u'isYe
ar': u'0', u'isAutoDeduct': u'0', u'vipLevel': u'1', u'payName': u'\u6dd8\u5b9d\
u76f4\u5145', u'vasid': u'14', u'isVip': u'0', u'vasType': u'3', u'vipDayGrow':
u'12', u'vipGrow': u'0'}]

20180528以前我既开通了快鸟会员， 又开通了上行提速会员， 20180528以后我只开通了快鸟上行提速会员，使用快鸟官方WINDOWS客户端登陆，上行提速成功。   使用脚本却提示出错， 请大神帮忙解决下， 谢谢！

**Comment by StartZYP** [comment]
我也有这个问题。。。用他那个老版本就行了

**Comment by fffonion** [comment]
已更新，请尝试新版：）

**Comment by fffonion** [comment]
默认解决，关闭老帖：）
