### ISSUE TITLE
开机启动后退出

### ISSUE THREAD

**Issue by frostnotfall** [fffonion/Xunlei-Fastdick#143]
路由器 R6300 v2
固件：梅林7.9
运行方式：sh脚本
启动脚本 /jffs/scripts/wan-start 内容：
nohup /jffs/scripts/swjsq > /dev/null 2>&1 &

最近的版本中，路由器重启后，swjsq文件启动后会退出，梅林官方说 wan-start 文件执行时网络可能还未准备好，所以估计是检测 wget 或 curl 的时候发现网未连通然后退出的。
路由器启动后手动执行不会出现问题。

虽然可能是梅林固件的问题，但还是希望作者能加入一下检测网络连通情况的设定。

**Comment by fffonion** [comment]
这个建议你安装生成的ipk，不要直接使用.sh文件，因为ipk里带了启动脚本，可以自动重试

**Comment by frostnotfall** [comment]
可能梅林固件有问题，nohup /jffs/scripts/swjsq > /dev/null 2>&1 & 运行后关闭终端，swjsq进程就消失了，应该是最近版本的问题。
/bin目录只读，也不存在/etc/init,d目录，所以ipk文件安装后不能用。
现在解决的办法是：
由于梅林已经安装了Entware，所以又安装了tmux
 /jffs/scripts/wan-start文件加入一下内容：
/opt/bin/tmux new -s swjsq -d
/opt/bin/tmux send -t "swjsq" "/bin/ash /jffs/scripts/swjsq" Enter
