### ISSUE TITLE
下载不支持提速时，提速上传错误

### ISSUE THREAD

**Issue by RainCat1998** [fffonion/Xunlei-Fastdick#144]
# 背景：
最近7月电信免费提速下载，原来100M下载带宽变成了200M下载带宽，但是200M宽带上传仅为6M，在为提速前，本人购买了迅雷上传和下载的提速包，一切使用正常，目前升级后无法使用脚本提速。

# 分析：
因为下载提速最多提速到200M，目前升级后下行带宽已经提速到200M，当然不能提速。并且在迅雷快鸟软件中，下载提速也显示不支持提速。但是上传提速依旧有效。

# 脚本逻辑bug：
本脚本提速的逻辑是，先使用迅雷的接口判断是否支持提速，如果不支持则不会提速。但是迅雷的接口只是判断下载能否提速，并不代表上传不能提速。这就是出现此问题的原因。

# 临时解决方案：
在脚本380行后添加如下代码：
`self.do_down_accel = False		#up_accel only`

修改代码后脚本暂时解决此问题，希望作者能针对此情况对脚本进行修改。
此外十分感谢作者对项目开发和维护。

**Comment by fffonion** [comment]
检查下载是否能提速应该不会影响判断上传，是使用的10天前更新的版本吗？

**Comment by RainCat1998** [comment]
不是，使用的最新的版本。

**Comment by fffonion** [comment]
能否贴一下脚本提示退出时报错的信息？

**Comment by RainCat1998** [comment]
现在超级会员过期没法复现了，之前的错误如下：
`08:34:15 Login xunlei succeeded
08:34:15 Expire date for chaoji member: 20181030
08:34:15 Expire date for upstream acceleration: 20181018
08:34:16 Warning: fastdick can not upgrade, so sad TAT: 电信线路暂不支持
08:34:16 To Upgrade: **电信 up 6M -> 20M
08:34:16 Initializing upgrade
08:34:16 Upstream error 502: dial_acct is null
08:34:59 Sending recover request
07:54:13 Login xunlei succeeded
07:54:13 Expire date for chaoji member: 20181030
07:54:13 Expire date for upstream acceleration: 20181018
07:54:14 To Upgrade: **电信 up 6M -> 20M
07:54:14 Initializing upgrade
07:54:15 Upgrade done: up 200M
07:54:23 Sending recover request
`
检测的不是下载是否能够提速，而是下载提速是否出错。
你检测是是否开通下行加速会员，但并不代表能够提速，比如你的带宽已经达到提速上限，但是你的下行加速没有过期。

**Comment by fffonion** [comment]
api返回能否提速的信息被忽略是因为之前有很多用户反应这个api的检测值不靠谱，所以现在的逻辑是不管能不能提速都试一下，如果提速出错再退出。

**Comment by fffonion** [comment]
关闭未活跃issue，如有需要请重新打开：）
