### ISSUE TITLE
Python启动失败

### ISSUE THREAD

**Issue by Squaregentleman** [fffonion/Xunlei-Fastdick#146]
日志
20:53:29 Warning: get interface_ip failed, use fallback address
20:53:30 Warning: get interface_ip failed, use fallback address
20:53:30 Login xunlei succeeded
20:53:30 Expire date for fastdick: 20181007
20:53:31 Warning: error during downapi connection: <urlopen error [Errno 146] Connection refused>, use portal: 119.147.41.210:12180
20:53:31 Error: can't connect to down api

**Comment by fffonion** [comment]
这个应该是偶现错误？

**Comment by fffonion** [comment]
关闭未活跃issue，如有需要请重新打开：）
