### ISSUE TITLE
启动后提示UnicodeDecodeError

### ISSUE THREAD

**Issue by MEZboy** [fffonion/Xunlei-Fastdick#147]
具体信息如下
root@ubnt:/mnt/swjsq# python ./swjsq.py 
11:02:29 Login xunlei succeeded
11:02:30 Expire date for fastdick: 20191202
11:02:30 To Upgrade: 北京联通 down 200M -> 500M
11:02:30 Initializing upgrade
11:02:31 Traceback (most recent call last):
  File "./swjsq.py", line 479, in run
    api_ret = self.api('upgrade', extras = "user_type=1&dial_account=%s" % _dial_account)
  File "./swjsq.py", line 332, in api
    ret[_k1] = json.loads(http_req(url, headers = header_api))
  File "./swjsq.py", line 188, in http_req
    ret = buf.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb8 in position 96: invalid start byte

**Comment by fffonion** [comment]
我这没有复现，如果有问题请重新打开issue
