### ISSUE TITLE
超级会员加速获取失败

### ISSUE THREAD

**Issue by InsistDon** [fffonion/Xunlei-Fastdick#149]
10:10:36 Login xunlei succeeded
10:10:36 Expire date for chaoji member: 20190823
10:10:36 To Upgrade: 北京联通 down 200M -> 500M
10:10:36 Initializing upgrade
10:10:38 Upgrade done: down 0M

**Comment by donghaoranx99** [comment]
如果您需要我可以提供我的超级会员账号给您测试

**Comment by fffonion** [comment]
这个感觉是迅雷的问题，建议测一下加速后的网速？

**Comment by fffonion** [comment]
关闭未活跃issue，如有需要请重新打开：）
