### ISSUE TITLE
在PC上swjsq_wget.sh不能用了，但是swjsq.py还可以

### ISSUE THREAD

**Issue by newKingg** [fffonion/Xunlei-FastDick#15]
显示 "client_type":"","errno":513,"message":"not exist channel", ...
另外 swjsq.py 开头为什么不添加一行 #!/usr/bin/env python 呢

**Comment by fffonion** [comment]
这个貌似并不是脚本的问题……
建议重新拨下号
#!那个可以加上

**Comment by fffonion** [comment]
see #15
