### ISSUE TITLE
使用新接口实现了一版

### ISSUE THREAD

**Issue by vcheckzen** [fffonion/Xunlei-Fastdick#152]
目前没有出现无法提速，提速无效果和要求输验证码等情况。但为了长期使用我并不想开源，若有朋友需要可以给我发邮件，无意打扰此项目，仅仅为了方便无法使用的朋友

![ATQTLd.png](https://s2.ax1x.com/2019/04/10/ATQTLd.png)
![ATQHeA.jpg](https://s2.ax1x.com/2019/04/10/ATQHeA.jpg)

**Comment by fffonion** [comment]
Consider offtopic, closing
