### ISSUE TITLE
这个报错是什么意思？

### ISSUE THREAD

**Issue by yizhitangtongxue** [fffonion/Xunlei-Fastdick#154]
版本：装的IPK
固件版本：路由器上的老毛子3.4.3.9-099_8-06-05
错误日志：
May  3 23:38:07 【FastDicks】:  23:38:07 keepalive
May  3 23:38:07 【FastDicks】:  sh: operate: unknown operand

**Comment by frostnotfall** [comment]
同问，报错信息：

{"bandwidth":{"downstream":0,"upstream":0},"button_data":{"can_click":0,"can_click_time":0,"link_url":"","name":"","on_click_type":0},"errno":500,"hover_bubble":"","is_button":0,"is_text":0,"message":"send operate channel msg to speedup server failed","prov_id":0,"richmessage":"抱歉，服务器请求出错，请重试","sp_id":0,"timestamp":1557060255}

**Comment by yizhitangtongxue** [comment]
@frostnotfall 我的解决了，重新生成了一下swjsq_wget.sh，然后拷贝到设置里就行了

**Comment by frostnotfall** [comment]
好的，回头我试试

**Comment by fffonion** [comment]
@frostnotfall 你这个报错应该是迅雷的服务器爆炸了，可以多试几次看是不是可以重现

**Comment by frostnotfall** [comment]
问题解决了， 我是使用脚本方式运行，按照@yizhitangtongxue 的方法，重新生成swjsq脚本，应该是脚本中记录了一些状态，而状态过期了。估计ipk方式安装的同学不会有此问题。
感谢 @yizhitangtongxue 、 @fffonion 回复。

**Comment by fffonion** [comment]
如有问题请重新打开issue : )
