### ISSUE TITLE
Downstream error 812: speedup server already speed up

### ISSUE THREAD

**Issue by XHXJ** [fffonion/Xunlei-Fastdick#159]
05:27:43 Initializing upgrade
05:27:43 Downstream error 812: speedup server already speed up
05:27:43 Downstream already upgraded, continuing

无法加速

**Comment by frostnotfall** [comment]
在局域网其他设备或app下加速过后，会是这个样子。
光猫重新拨号试试

**Comment by XHXJ** [comment]
好的谢谢
