### ISSUE TITLE
u'not exist channel错误……

### ISSUE THREAD

**Issue by cor961** [fffonion/Xunlei-FastDick#16]
你好，我是安装在QNAP的NAS上，其中swjsq_0.0.1_all.ipk安装后产生的swjsq无法正常运行，swjsq_wget.sh运行后无效果，我是直接用以下语句建了个sh直接让swjsq.py运行的（虚拟为qpkg以便开机启动）：
#!/bin/sh
QPKG_NAME="Xunlei-FastDick"
cd /share/HDA_DATA/.qpkg/Xunlei-FastDick
/share/HDA_DATA/.qpkg/Python/bin/python /share/HDA_DATA/.qpkg/Xunlei-FastDick/swjsq.py --daemon
运行正常时能正常加速，现在的问题是运行一段时间后出现结尾为u'not exist channel的错误，且经测试此时已无加速效果。
请问此错误代表什么含义？有无可能的解决方法？
谢谢。

**Comment by fffonion** [comment]
没有解决办法，只能尝试恢复原始速度(recover)再重新加速(upgrade)

**Comment by cor961** [comment]
好的，谢谢，我试下能不能设成定时重启来解决这个问题。

**Comment by shenwei356** [comment]
同问题。上次是断开网线几分钟后恢复的，这次不行了。

**Comment by shenwei356** [comment]
update: 昨晚重启路+拔网线由也无效，今天上午却可以了。

**Comment by fffonion** [comment]
@shenwei356 我家里跑着的也有时会not exist channel，但可以肯定的是如果不去管它，过一会会自己恢复；所以目测不是脚本的问题也不是迅雷的问题，初步怀疑是运营商那里的问题（有可能接口抽了或者某些时段不让加速）
希望大家能在这里贴一下：
1. 运营商（如上海电信）
2. 出现not exists channel的时间段
3. 出现错误后恢复正常的时间
也许从统计中可以有一些发现 ;-)

**Comment by cor961** [comment]
查了下，出现次数还不少，都是在14:25~14:54、20:21~20:59、15:48~16:26、10:28~11:06、14:58~15:36、16:45~18:15、4:12~4:50、14:37~15:16（log里没有日期只有时间啊……），时间段上没发现什么规律，不过一般持续半小时左右后就恢复了，四川电信。

**Comment by fffonion** [comment]
@cor961 嗯，感谢
30分钟正好是重新发upgrade的时间……
虽然不知道为什么中途会失效
试一下新版吧现在收到not exist channel会重新upgrade，应该可以解决这个问题了

**Comment by cor961** [comment]
Error: speedup server already speed up
Traceback (most recent call last):
  File "/share/HDA_DATA/.qpkg/Xunlei-FastDick/swjsq.py", line 249, in fast_d1ck
    if errno == 513:# TEST: re-upgrade when get 'not exist channel'
NameError: global name 'errno' is not defined

**Comment by fffonion** [comment]
我傻逼了hhh
