### ISSUE TITLE
安装curl与wget后仍然有cannot find wget or curl installed with https(ssl) enabled in this system.

### ISSUE THREAD

**Issue by White-Clouds** [fffonion/Xunlei-Fastdick#162]
系统日志：
Thu Jan  2 12:02:31 2020 daemon.err swjsq[16050]: Segmentation fault
Thu Jan  2 12:02:31 2020 daemon.err swjsq[16050]: Xunlei-FastD1ck cannot find wget or curl installed with https(ssl) enabled in this system.

已安装curl和https支持的wget，仍然报错。

**Comment by zh99998** [comment]
`with https(ssl) enabled`

**Comment by fffonion** [comment]
前面有个段错误，可能是链接的动态库不太对
试试直接运行
wget https://baidu.com -q -O /dev/null
和
curl https://baidu.com -s -o /dev/null
