### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by Decwind** [fffonion/Xunlei-Fastdick#165]
没有办法保持心跳，总是需要重启才生效，f大能不能更新一下

**Comment by pingshu** [comment]
一样的问题
13:01:24 Initializing upgrade
13:01:24 Upgrade done: down 200M
19:05:23 Downstream error 513: not exist channel
19:05:23 Initializing upgrade
19:05:28 Downstream error 711: client request too frequent

**Comment by fffonion** [comment]
#160
