### ISSUE TITLE
极路由可以用吗

### ISSUE THREAD

**Issue by PRAJNAPLAYER** [fffonion/Xunlei-Fastdick#166]
非常需要

**Comment by fffonion** [comment]
https://www.frost.net.cn/archives/40 试试？

原生插件是没有的

**Comment by PRAJNAPLAYER** [comment]
现在脚本还是可以成功加速和保持心跳吧？那我研究研究，纯小白 哈哈哈

**Comment by PRAJNAPLAYER** [comment]
作者大佬方便协助下吗

**Comment by PRAJNAPLAYER** [comment]
17:27:03 Login xunlei succeeded
17:27:04 Expire date for fastdick: 20200711
17:27:04 Warning: fastdick can not upgrade, so sad TAT: get ip info failed!
17:27:04 Error: neither downstream nor upstream can be upgraded

**Comment by PRAJNAPLAYER** [comment]
无法登录

**Comment by fffonion** [comment]
@PRAJNAPLAYER 
看错误信息是迅雷接口出错，如果仍有问题请冲开issue
