### ISSUE TITLE
无法对容器设置时区

### ISSUE THREAD

**Issue by lnc1995** [fffonion/Xunlei-Fastdick#183]
TZ参数不能被容器识别处理，有些Docker环境下会导致时间不正确

**Comment by xrzlddl** [comment]
-v /etc/localtime:/etc/localtime:ro 
docker run增加这个挂载把本地的时区挂载到容器即可！

**Comment by lnc1995** [comment]
> -v /etc/localtime:/etc/localtime:ro docker run增加这个挂载把本地的时区挂载到容器即可！

也许有的环境可以。我用的RouterOS不行。可以用以下方法：
镜像运行以后，进入镜像shell。
apk add tzdata
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
echo "Asia/Shanghai" > /etc/timezone

**Comment by xrzlddl** [comment]
这个要查下 routeros的时区文件在什么地方存着了，找到后  挂载下就可以了

**Comment by lnc1995** [comment]
> 这个要查下 routeros的时区文件在什么地方存着了，找到后 挂载下就可以了

ROS本身就存在时区的问题，加上系统封闭，这个操作行不通。只能对容器本身操作
