### ISSUE TITLE
重复显示 " session is empty "?

### ISSUE THREAD

**Issue by yaodwwy** [fffonion/Xunlei-FastDick#20]
session is empty
--2015-10-18 10:50:32--  https://login.mobile.reg2t.sandai.net/
Resolving login.mobile.reg2t.sandai.net... 123.150.173.198
Connecting to login.mobile.reg2t.sandai.net|123.150.173.198|:443... connected.
WARNING: cannot verify login.mobile.reg2t.sandai.net's certificate, issued by '/C=CN/ST=shenzhen/L=sz/O=xl\\x08/OU=huiyuan/CN=xl':
  Self-signed certificate encountered.
    WARNING: certificate common name 'xl' doesn't match requested host name 'login.mobile.reg2t.sandai.net'.
HTTP request sent, awaiting response... 200 OK
Length: 177 [application/octet-stream]
Saving to: 'STDOUT'

**Comment by fffonion** [comment]
你没改过密码吧？登陆迅雷客户端的时候要不要输验证码什么的

**Comment by yaodwwy** [comment]
密码不错，不需要输验证码。我还有一个疑问：在路由器界面里的“本地启动脚本”增加的swjsq启动项，与/etc/inittab文件里增加：::respawn: swjsq 有什么区别吗？ 如果在其它客户端登录了快鸟，在路由器端的会自动下线而失效吗，需不需要加入到计划任务中去？ 如果加入到计划任务中，会在进程中多现多条记录，如何仅单进程运行？

**Comment by fffonion** [comment]
1. 我不知道有啥区别
2. 路由器端可能会收到not exist channel然后重新登录，然后把其他客户端的挤掉
3. 不要加到计划任务，开机启动一次就行了，会一直在后台跑的

**Comment by yaodwwy** [comment]
最后一个问题，在自动生成的swjsq_wget.sh文件和ipk里面的swjsq文件对比下来是一样的.那我在直接执行.sh文件不是一样的启动吗? 另外如果在执行的时候，显示文件或目录Not found，但实际是有该文件的，请问您知道是什么问题吗？

**Comment by fffonion** [comment]
ipk是可以安装的，安装之后会把sh放到/bin里并加上执行权限。用哪个无所谓
前面加上`./`

**Comment by yaodwwy** [comment]
谢谢热心回复

**Comment by fffonion** [comment]
![p2e_dsv lb1o q7ztwod6g2](https://cloud.githubusercontent.com/assets/2135445/10623341/3b88a0d6-775c-11e5-8213-a55840fd43b0.jpg)
