### ISSUE TITLE
账号加密的文件不生成

### ISSUE THREAD

**Issue by CheukFung** [fffonion/Xunlei-Fastdick#23]
密文账号文件不生成，明文删除之后就要重新设置了。

**Comment by fffonion** [comment]
你好，能否给一个重现的步骤？

**Comment by CheukFung** [comment]
ubuntu 14.04,自带的Python执行python swjsq.py之后，提速成功。生成ipk,sh,log文件，swjsq.account.txt文件被删除，没有其他文件生产。newifi上pandorabox，python版本，2.7.3，同样问题。都没有安装pycrypto。是否是我的环境问题？谢谢

**Comment by fffonion** [comment]
生成的文件是.开头的，需要显示隐藏文件，或者`ls -a`

**Comment by akar1nchan** [comment]
�  Xunlei-FastDick git:(master) � ls -a
.   .git        Readme.MD  swjaq.account.txt    swjsq.py
..  .gitignore  go.sh      swjsq.account.b.txt
�  Xunlei-FastDick git:(master) � python swjsq.py
Please create config file "swjsq.account.txt", input account splitting with comma(,). Eg:
yonghuming,mima

**Comment by akar1nchan** [comment]
发现每次会丢失txt 就写了b.txt备份 现在pull了新版本的就无法启动了

**Comment by akar1nchan** [comment]
Login xunlei succeeded
To Upgrade: shang_hai tel Down 20M -> 30M, Up 2M -> 20M
Initializing upgrade
Upgrade done: Down 30M, Up 0M
Traceback (most recent call last):
  File "swjsq.py", line 414, in <module>
    fast_d1ck(uid, pwd_md5, TYPE_NUM_ACCOUNT, save = False)
  File "swjsq.py", line 258, in fast_d1ck
    open('swjsq.log', 'a').write('%s %s\n' % (time.strftime('%X', time.localtime(time.time())), _))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 74-75: ordinal not in range(128)
Sending recover request

**Comment by fffonion** [comment]
258行这个的确有编码的问题，但是感觉应该不是很有关系
另外既然运行到line 414，那说明`account_file_encrypted = '.swjsq.account'`这个文件是存在的，代码里没有删除这个文件的逻辑，按道理说不会消失啊
: (

**Comment by fffonion** [comment]
@akar1nchan 我这里没法复现bug，能否麻烦从进入fast_d1ck方法开始插几个raw_input()看下这个文件是在哪里开始消失的

**Comment by CheukFung** [comment]
@fffonion 原来如此，谢谢
