### ISSUE TITLE
目前快鸟需要30元一月的钻石会员。

### ISSUE THREAD

**Issue by yaodwwy** [fffonion/Xunlei-FastDick#26]
目前快鸟需要30元一月的钻石会员。只能呵呵了

**Comment by cor961** [comment]
你迅雷帐号等级低了吧，我淘宝充的6~8元/月都充了几次了，从20M升到50M，还是挺值的。

**Comment by fffonion** [comment]
这里仅供讨论脚本相关问题，请不要讨论无关话题: )
