### ISSUE TITLE
快鸟会员提示失败

### ISSUE THREAD

**Issue by tamen2** [fffonion/Xunlei-Fastdick#27]

**Comment by fffonion** [comment]
请详细描述问题

**Comment by tamen2** [comment]
非迅雷白金，近期购买的 快鸟会员，提示非会员

**Comment by fffonion** [comment]
这里仅供讨论脚本相关问题，请不要讨论无关话题

**Comment by 56878263** [comment]
C:\Python27>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Error: you are not xunlei vip, buy buy buy! http://vip.xunlei.com/

非迅雷白金，近期购买的 快鸟会员，提示非会员

**Comment by fffonion** [comment]
@56878263 试下最新的commit，在buy buy buy下面加了一行debug，贴一下你那里输出了什么：）

**Comment by 56878263** [comment]
Warning: pycrypto not found, use pure-python implemention
Error: you are not xunlei vip, buy buy buy! http://vip.xunlei.com/
[Debug] isVip:0 payId:0 payName:[u'----']

**Comment by fffonion** [comment]
不科学啊……
payname那里是什么？

**Comment by 56878263** [comment]
C:\Windows\system32>cd C:\Python27

C:\Python27>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Error: you are not xunlei vip, buy buy buy! http://vip.xunlei.com/
[Debug] isVip:0 payId:0 payName:[u'----']

C:\Python27>

这是全部了

**Comment by fffonion** [comment]
算了我把vip判断去掉好了……

**Comment by 56878263** [comment]
好,谢谢,我可以把号给你做测试用.

**Comment by fffonion** [comment]
@56878263 没事，我感觉是迅雷通过别的借口判断是不是快鸟会员了
我把那个buy buy buy改成warning了，应该不影响使用了

**Comment by 56878263** [comment]
session is empty
session is empty
session is empty

过一段时间就会变成这样。。。
webshell就会不停的刷这个。大概3,4秒钟两个

**Comment by 56878263** [comment]
在进程里看到好多 swjsq ..
 27271    root   {swjsq} /bin/ash /bin/swjsq

**Comment by fffonion** [comment]
@56878263 登陆次数太频繁了？
应该不会有好多swjsq啊，难道你是设置了定时任务？这个脚本启动以后不会退出的

**Comment by 56878263** [comment]
我只是在启动里写了一行。
# Put your custom commands here that should be executed once
# the system init finished. By default this file does nothing.
(/bin/swjsq &)        写了这行

exit 0

**Comment by fffonion** [comment]
那应该不会有好多swjsq啊
session is empty就是登陆失败，建议pc上登一下迅雷账号，或者用python版看下登陆报什么错

**Comment by 56878263** [comment]
用pc的快鸟客户端直接登陆了，没有任何错误提示。

**Comment by fffonion** [comment]
试下python版

**Comment by 56878263** [comment]
C:\Python27>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Error: login failed, 您的帐号存在异常,请登录安全中心确认！

**Comment by fffonion** [comment]
登陆次数太多了

**Comment by 56878263** [comment]
为什么这样呢。。。下班回来就这样了。
之前也会这样

**Comment by fffonion** [comment]
不太清楚，感觉你得研究下为什么会有好多swjsq，这个解决了应该就不会有账号异常了

**Comment by 56878263** [comment]
好的。谢谢，又麻烦你。

**Comment by fffonion** [comment]
不客气

**Comment by 56878263** [comment]
又来麻烦你了。。。
--------------------------------------------
/www# /bin/swjsq
--------------------------------------------

session is 456719AFB7F4C065A74481F0C6F948B8
uid is empty
{"bandwidth":{"downstream":102400,"upstream":0},"dial_account":"170035176155","errno":0,"message":"","province":"bei_jing","province_name":"北京","sequence":0,"sp":"cnc","sp_name":"联通","timestamp":1448808086}

无加速效果。

**Comment by 56878263** [comment]
C:\Python27>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Warning: you are probably not xunlei vip, buy buy buy!
[Debug] isVip:0 payId:0 payName:[u'----']
Login xunlei succeeded
To Upgrade: 北京联通 Down 50M -> 100M, Up 0M -> 0M
Initializing upgrade
Upgrade done: Down 102400M, Up 0M

这个正常加速了。

**Comment by fffonion** [comment]
@56878263 之前有人发过一个issue说某些情况下grep正则会失效，一下子找不到了
能否在脚本里echo uid is empty前加一行
echo $ret
然后把结果贴一下

**Comment by lalalashuibuzhao** [comment]
@fffonion 
我用路由器跑脚本会出现乱码所以用PC直接跑脚本的结果，把ash换成bash跑的
session is empty
--2015-12-03 02:18:32--  https://login.mobile.reg2t.sandai.net/
正在解析主机 login.mobile.reg2t.sandai.net (login.mobile.reg2t.sandai.net)... 123.150.173.198
正在连接 login.mobile.reg2t.sandai.net (login.mobile.reg2t.sandai.net)|123.150.173.198|:443... 已连接。
警告: 无法验证 login.mobile.reg2t.sandai.net 的由 “CN=xl,OU=huiyuan,O=xl\\08,L=sz,ST=shenzhen,C=CN” 颁发的证书:
  出现了自己签名的证书。
    警告: 证书通用名 “xl” 与所要求的主机名 “login.mobile.reg2t.sandai.net” 不符。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：177 [application/octet-stream]
正在保存至: “STDOUT”

-                   100%[=====================>]     177  --.-KB/s 用时 0s     

2015-12-03 02:18:32 (31.0 MB/s) - 已写入至标准输出 [177/177]

**Comment by fffonion** [comment]
@lalalashuibuzhao 你和56878263是同一个人不……
先加一行echo $ret再贴下结果，主要是看session is empty之前的输出

**Comment by lihan1992** [comment]
显示非会员是迅雷官方问题，现在已解决，至少我的解决了，不是这里的问题
感觉是因为新出的快鸟会员与原会员体系不同造成的

**Comment by fffonion** [comment]
@lihan1992 是我本地做的判断，现在已经去掉了

**Comment by lihan1992** [comment]
@fffonion 
uid is empty
{"bandwidth":{"downstream":30,"upstream":0},"dial_account":"he::IP15519107818","errno":0,"message":"","province":"he_bei","province_name":"河北","sequence":0,"sp":"tel","sp_name":"电信","timestamp":1449149111}
uid is empty正常吗？

**Comment by lalalashuibuzhao** [comment]
@fffonion 我和他不是一个人 
{"isequenceNo":1000001,"errorDesc":"�ʺŲ����ڣ�����������","errorCode":2,"errorIsRetry":0,"cmdID":2,"protocolVersion":101,"sCompressed":0,"platformVersion":1,"errorDescUrl":""}

**Comment by fffonion** [comment]
@lihan1992 只要能提速应该是没问题的，可以先在PC上完整地加速->退出(ctrl+c)一次，再在路由器上测试，如果成功提速，那可以忽略uid的问题；因为对API是黑盒分析，可能迅雷那边并不需要uid
@lalalashuibuzhao 最好能看到errorDesc的乱码内容……试下echo $ret >/tmp/aaa然后取回PC看下？

**Comment by 56878263** [comment]
请教问题。 我路游戏刷的是pandorabox系统，为什么把(/bin/swjsq)放到启动项里，swjsq不会随路由器启动而启动吗？  放到了  exit 0 上一行。重启路由器，进程里没有swjsq。
必须手动执行才会有进程{swjsq} /bin/ash /bin/swjsq 
还有，手动启动swjsq后，有加速效果，但是过段时间（具体不知道多久），一般都是下班回来后已经没有加速效果了。python运行加速成功，不重启路由的情况下，webshell下执行/bin/swjsq没有加速效果，但是输出和正常加速没有区别。

**Comment by lihan1992** [comment]
@fffonion OK，用了新的swjsq没有问题了，之前加速一段后会失效，才问的是不是UID为空的问题
@56878263 你试试新的swjsq

**Comment by 56878263** [comment]
@lihan1992 用的是最新的swjsq，感觉是账号从别的地方登陆后，或是加速断开一次后脚本没有再次自动连接的缘故。

**Comment by fenghn888** [comment]
快鸟会员年费用户，在` login_xunlei(uname, pwd, login_type)`以后，print出来是这样的
```
    "isVip": 0,
    "isYear": 1,
    "payId": 5,
    "payName": "年费支付方式",
```
