### ISSUE TITLE
swjsq_wget.sh是必须的文件？

### ISSUE THREAD

**Issue by hdstar2009** [fffonion/Xunlei-FastDick#33]
如果路由器硬件限制无法安装Python，也可以在PC上运行脚本，登陆成功后会生成swjsq_wget.sh以及一个ipk包，将生成的ipk安装进路由器即可；需要路由器安装支持https的wget或curl

swjsq_wget.sh这个需要放到路由器里面？还是说ipk安装后就可以了？
之前的账号信息是否已经整合到ipk里面了？

**Comment by ninggu2008** [comment]
ipk算安装包，不透明，目的是傻瓜式安装脚本。如果懂的话，自己把sh脚本放到路由适当目录、改权限、加自启。
账号信息已经整合了。否则没必要运行后才生成脚本。

**Comment by fffonion** [comment]
@ninggu2008 正解
