### ISSUE TITLE
speedup server already speed up

### ISSUE THREAD

**Issue by tianweb** [fffonion/Xunlei-FastDick#34]
root@Morz:~python swjsq.py
Login xunlei succeeded
To Upgrade: 辽宁电信 Down 4M -> 30M, Up 4M -> 100M
Initializing upgrade
Error: speedup server already speed up

rooot@Morz:~/Xunlei-FastDick# ./*.sh
--2015-12-10 21:36:33--  https://login.mobile.reg2t.sandai.net/
正在解析主机 login.mobile.reg2t.sandai.net (login.mobile.reg2t.sandai.net)... 123.150.173.198
正在连接 login.mobile.reg2t.sandai.net (login.mobile.reg2t.sandai.net)|123.150.173.198|:443... 已连接。
警告: “login.mobile.reg2t.sandai.net” 的证书不可信。
警告: “login.mobile.reg2t.sandai.net” 的证书颁发者未知。
证书所有者与主机名 “login.mobile.reg2t.sandai.net” 不符
已发出 HTTP 请求，正在等待回应... 200 OK
长度：177 [application/octet-stream]
正在保存至: “STDOUT”

-                             100%[=================================================>]     177  --.-KB/s  用时 0s    

2015-12-10 21:36:34 (50.1 MB/s) - 已写入至标准输出 [177/177]

session is empty
--2015-12-10 21:36:39--  https://login.mobile.reg2t.sandai.net/
正在解析主机 login.mobile.reg2t.sandai.net (login.mobile.reg2t.sandai.net)... 123.150.173.198
正在连接 login.mobile.reg2t.sandai.net (login.mobile.reg2t.sandai.net)|123.150.173.198|:443... 已连接。
警告: “login.mobile.reg2t.sandai.net” 的证书不可信。
警告: “login.mobile.reg2t.sandai.net” 的证书颁发者未知。
证书所有者与主机名 “login.mobile.reg2t.sandai.net” 不符
已发出 HTTP 请求，正在等待回应... 200 OK
长度：177 [application/octet-stream]
正在保存至: “STDOUT”

-                             100%[=================================================>]     177  --.-KB/s  用时 0s    

2015-12-10 21:36:39 (40.7 MB/s) - 已写入至标准输出 [177/177]

session is empty

结果 并没有成功加速 原先py的还能用 现在的py的也不行了
脑版加速可用

**Comment by fffonion** [comment]
用pc版运行一次然后ctrl+c退出恢复原速，再重新运行加速
或者重新拨个宽带换ip

**Comment by tianweb** [comment]
话说py版能不能在做一份不会生成ipk的呢= = 目前py版可用
非常感谢 
（本人路由是自己用一台低功耗搭的 系统：debian sid  openwrt有关的对我来说都用不上

**Comment by fffonion** [comment]
@tianweb 不太明白你的意思？

**Comment by tianweb** [comment]
就是想让您做一份不会生成ipk包的py的迅雷加速脚本

**Comment by fffonion** [comment]
@tianweb 你可以假装没看到ipk😉
