### ISSUE TITLE
运行后提示一下错误

### ISSUE THREAD

**Issue by segasonicye** [fffonion/Xunlei-Fastdick#35]
运行后提示一下错误，求解
C:\Python27>python.exe swjsq.py
Traceback (most recent call last):
  File "swjsq.py", line 446, in <module>
    uid, pwd = open(account_file_plain).read().strip().split(',')
ValueError: need more than 1 value to unpack

**Comment by fffonion** [comment]
账号文件里是需要用逗号隔开的，而且是半角的逗号，不是中文的全角逗号
√ -> ,
× -> ，

**Comment by segasonicye** [comment]
已解决，感谢

**Comment by fffonion** [comment]
![qq 20160221024055](https://cloud.githubusercontent.com/assets/2135445/13200533/a39b5f46-d81a-11e5-9015-bf63c5f91414.png)
