### ISSUE TITLE
无法储存swjsq，默认保存在/bin，目录不可写入。

### ISSUE THREAD

**Issue by silicaite** [fffonion/Xunlei-Fastdick#38]
root@unknown:/tmp# opkg install swjsq_0.0.1_all.ipk
Installing swjsq (0.0.1) to root...
Configuring swjsq.
Collected errors:
- wfopen: /bin/swjsq: Read-only file system.

tomato arm系统。
不知该如何解决？谢谢！

**Comment by fffonion** [comment]
415行的./bin/swjsq改成可写的目录就可以了，删除ipk文件然后重新运行python脚本就可以生成新的ipk
或者直接将swjsq_wget.sh拷入路由器，加上执行权限

**Comment by silicaite** [comment]
改过后，生成的swjsq，运行后提示：
Xunlei-FastD1ck cannot find wget or curl installed with https(ssl) enabled in this system.
该如何解决？谢谢！

**Comment by fffonion** [comment]
不客气🌚

**Comment by ky0ncheng** [comment]
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: 上海电信 Down 20M -> 30M, Up 4M -> 20M
Initializing upgrade
Error: 后端服务错误：time data '' does not match format '%Y%m%d%H%M%S'

**Comment by fffonion** [comment]
@ky0ncheng 这个是快鸟api那里返回的错误，我也没办法

等等这个后端竟然是python写的……
![qq 20160315061609](https://cloud.githubusercontent.com/assets/2135445/13768388/f34451ae-ea4b-11e5-970c-350a9ecc609e.jpg)

**Comment by ky0ncheng** [comment]
@fffonion 好吧 可能是迅雷那边大姨妈了 我先用菊花牌安卓机客户端挂着吧~

**Comment by fffonion** [comment]
@ky0ncheng 嗯 我这里没有这问题 等他们修吧

**Comment by ky0ncheng** [comment]
挂在快鸟看李世石感觉不卡了

**Comment by fffonion** [comment]
hhhhhh
