### ISSUE TITLE
session is empty

### ISSUE THREAD

**Issue by qiumzh** [fffonion/Xunlei-Fastdick#42]
运行几天后突然就不行了，再次登录路由器运行（重启再运行，重装再运行），都提示session is empty ，请问有什么解决办法吗？（PS：在PC端用python运行swjsq.py 是可以提速，但是在路由上就不行 ，老是提示session is empty）求搭救。

**Comment by fffonion** [comment]
试一下用最新版本，删掉.sh重新生成一遍。
最近的两个提交应该已经解决这个问题了

**Comment by qiumzh** [comment]
现在可以了，非常感谢
