### ISSUE TITLE
docker无法获取最新的镜像

### ISSUE THREAD

**Issue by yswtrue** [fffonion/Xunlei-Fastdick#46]
我用
docker pull flier/xunlei-fastdick
提示
Tag latest not found in repository docker.io/flier/xunlei-fastdick

所以只能用docker pull flier/xunlei-fastdick:flier_docker才可以获取镜像。
还有貌似这两天的加速没效果了。我也重启了这个docker还是不行。

**Comment by fffonion** [comment]
docker镜像的问题抄送 @flier 
加速没效果的话，请提供详细的信息，如使用官方客户端能否加速、docker logs等

**Comment by asaboss** [comment]
主要是TAG latest错误，所以没办法。我也是这个错误，把TAG换成flier_docker就好了

**Comment by flier** [comment]
之前是打算merge到原项目主版本树，所以单独建了个pull request分支，导致latest需要手工合并，一会儿我merge一下

asaboss <notifications@github.com>于2016年5月17日周二 05:38写道：

**Comment by flier** [comment]
merge 了最新代码到 https://github.com/flier/Xunlei-Fastdick/tree/master

手工创建了个 latest 的 image https://hub.docker.com/r/flier/xunlei-fastdick/tags/
