### ISSUE TITLE
不能用了  直接闪退  说账号异常要去安全中心确认

### ISSUE THREAD

**Issue by DeTeKe** [fffonion/Xunlei-Fastdick#47]

**Comment by ericwang2006** [comment]
我这里也是提示去安全中心认证, 用迅雷快鸟客户端是要输入一个验证码.

**Comment by ericwang2006** [comment]
我用的是python版

**Comment by ghy459** [comment]
楼上+1，今天也碰到这个问题了。。

**Comment by ghy459** [comment]
login_xunlei返回这串东西咯，就是要输验证码了，供参考

`{u'isequenceNo': 1000001, u'errorCode': 6, u'cmdID': 2, u'errorIsRetry': 0, u'protocolVersion': 101, u'platformVersion': 1, u'errorDesc': u'\u60a8\u7684\u5e10\u53f7\u5b58\u5728\u5f02\u5e38,\u8bf7\u767b\u5f55\u5b89\u5168\u4e2d\u5fc3\u786e\u8ba4\uff01', u'sCompressed': 0, u'errorDescUrl': u'http://verify2.xunlei.com/image?t=MEA'}`

**Comment by fffonion** [comment]
我看下

**Comment by wangchll** [comment]
抓了下包。。。发现app里请求多了两个值。。。devicesign和sdkVersion。。。另外，发现User-Agent	android-async-http/xl-acc-sdk/version-1.6.1.177600 再一次变了。。。

**Comment by fffonion** [comment]
@wangchll 主要是devicesign，而且apk还有壳哈哈哈哈

**Comment by wangchll** [comment]
@fffonion 这怎么玩。。。

**Comment by fffonion** [comment]
@wangchll 正在搞，可能需要一点时间

**Comment by fffonion** [comment]
迅雷应该是淘汰了旧的登录协议，之前脚本用的是protocolVersion是101
目前可以实现108的登录协议，我看下能不能搞出109的来，省得以后再麻烦ww

**Comment by TwoBall** [comment]
去快鸟论坛看了下验证码好像是全国性问题。而且我的mac迅雷登录也要验证码。不明白是个什么情况了

**Comment by fffonion** [comment]
用109的app好像不管安卓还是ios都有壳，谁会脱的话可以试试
和108之间只相差了一个盐

**Comment by asaboss** [comment]
Error: login failed, 您的帐号存在异常,请登录安全中心确认！。。。。挂了

**Comment by wangchll** [comment]
@fffonion 暂时108协议已经可以用了吧？我今天试下。。。愁人。。。109还是要搞那个签名算法。。。

**Comment by fffonion** [comment]
@wangchll 是的

**Comment by DeTeKe** [comment]
加速和心跳都没有问题 就是每30分钟keepalive就输出这个
`Traceback (most recent call last):
  File "D:\Program Files\Fastdick\swjsq.py", line 276, in fast_d1ck
    _ = api('upgrade', dt['userID'], dt['sessionID'])
TypeError: tuple indices must be integers, not str`

**Comment by wangchll** [comment]
@fffonion 我反编译了下看了下。。。竟然。用的是。。。com.qihoo360.crypt.entryRunApplication。。。这也太。。。贱了吧。。。。用360加壳。。。

**Comment by fffonion** [comment]
@wangchll 23333
btw之前的101老协议又可以用了

**Comment by wangchll** [comment]
@fffonion 我也发现了。。。醉了。。。

**Comment by hhalibo** [comment]
我今天使用python版，使用了最新的swjsq.py

还是提示：login failed，您的帐号异常，请登陆安全中心确认。

**Comment by fffonion** [comment]
@hhalibo 试一下登录pc迅雷是否需要验证码？

**Comment by asaboss** [comment]
@hhalibo 其实可以找迅雷客服，说账号异常。。。2天前也是这样，找了他们说了以后第二天早上起来就恢复了

**Comment by hhalibo** [comment]
@fffonion 在pc上登录迅雷快鸟，需要输入验证码的

**Comment by fffonion** [comment]
@hhalibo 那这应该是迅雷的问题

**Comment by yaoshu** [comment]
Error: login failed, 您的帐号存在异常,请登录安全中心确认！

**Comment by yaehei** [comment]
不能用了,您的帐号存在异常,请登录安全中心确认！

**Comment by DeTeKe** [comment]
Warning: pycrypto not found, use pure-python implemention
Error: login failed, 协议不合法，请联系客服确认！
{'errorIsRetry': 0, 'errorCode': 12, 'errorDescUrl': '', 'isequenceNo': 1000001, 'protocolVersion': 108, 'sCompressed': 0, 'platformVersion': 1, 'cmdID': 2, 'errorDesc': '协议不合法，请联系客服确认！'}
