### ISSUE TITLE
输出内容报编码错误

### ISSUE THREAD

**Issue by ghy459** [fffonion/Xunlei-FastDick#5]
部分server返回的内容会报编码错误：

Traceback (most recent call last):
  File "swjsq.py", line 380, in <module>
    fast_d1ck(uid, pwd_md5, TYPE_NUM_ACCOUNT, save = False)
  File "swjsq.py", line 216, in fast_d1ck
    _['max_bandwidth']['upstream']/1024,
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-15: ordinal not in range(128)

**Comment by fffonion** [comment]
请试一下设置环境变量的LANG和LC_CTYPE成zh_CN.UTF8（根据发行版不同可能略有不同
