### ISSUE TITLE
迅雷快鸟需要输入验证码，大神有办法绕开吗？

### ISSUE THREAD

**Issue by DonisChan** [fffonion/Xunlei-Fastdick#52]
这两天快鸟又失效了，查看了下是账号异常需要输入验证码，只有快鸟会这样，电脑端的快鸟也是，但是迅雷客户端不会弹验证码。手机端的快鸟也不会，有没可能像手机端的快鸟那样绕开验证码呢？

**Comment by fffonion** [comment]
我这里没法复现，请按照contributing.md补充信息

**Comment by DonisChan** [comment]
所使用的版本 (Python/Shell)
Python2.7 
运行的系统环境及版本 (操作系统，Python版本等)
win10
包含错误信息的日志:
{u'isequenceNo': 1000001, u'errorCode': 6, u'cmdID': 2, u'errorIsRetry': 0, u'protocolVersion': 101, u'platformVersion': 1, u'errorDesc': u'\u60a8\u7684\u5e10\u53f7\u5b58\u5728\u5f02\u5e38,\u8bf7\u767b\u5f55\u5b89\u5168\u4e2d\u5fc3\u786e\u8ba4\uff01', u'sCompressed': 0, u'errorDescUrl': u'http://verify2.xunlei.com/image?t=MEA'}

**Comment by fffonion** [comment]
@DonisChan 你用的是老版本的脚本，去https://github.com/fffonion/Xunlei-Fastdick/raw/master/swjsq.py下个新的吧

**Comment by DonisChan** [comment]
我在迅雷安全中心看了下，路由器一般是隔半个钟就运行脚本登陆一次快鸟，但是从提速失败后看到的就是隔3~5分钟就尝试登陆一次，是不是登陆太频繁引发的系统检测账号异常，导致需要输入验证码？我在公司打开电脑上的快鸟不需要输入验证码。

**Comment by fffonion** [comment]
protocolVersion=101的登录方式已经被弃用了，现在脚本已经改成108了，新的协议运行之后只需要登录一次
因为一直用101登陆失败，ip就被关照了（大概

**Comment by DonisChan** [comment]
昨天晚上试了新的脚本，会有中文的提示账号异常，和上面的那串错误信息。

**Comment by fffonion** [comment]
如果是快鸟客户端也需要验证码的话，就不是脚本的问题了

**Comment by DonisChan** [comment]
我觉得应该是因为快鸟脚本频繁登陆，触发的账号异常需要验证码。脚本有没可能绕过验证码呢？我在别的公司的网络下更新账号信息到脚本里面去，但是因为公司的网络不支持提速的，这样更新的脚本回去放进路由能生效吗？

**Comment by fffonion** [comment]
新版的脚本是不会频繁登陆的；如果在脚本外触发了验证码那我也无能为力了。更新的脚本仍然需要登录，所以还是会撞上验证码
建议停掉脚本过一段时间，如果之后快鸟客户端也需要验证码，那去找一下迅雷客服，论坛里有人被误判的例子

**Comment by DonisChan** [comment]
好的谢谢。
