### ISSUE TITLE
session is empty

### ISSUE THREAD

**Issue by ablmdream** [fffonion/Xunlei-Fastdick#54]
root@Hiwifi:~# killall -9 swjsq
root@Hiwifi:~# (/bin/swjsq &)
root@Hiwifi:~# login xunlei
session is empty
login xunlei
session is empty
login xunlei
session is empty
login xunlei
session is empty
login xunlei
session is empty

------------------------------------------------
大神，这个怎么破，刚安装的时候是可以的，运行几天就这样了；路由器每天重启，会不会和这个有关系？

**Comment by fffonion** [comment]
电脑登录看下是否需要验证码
