### ISSUE TITLE
大神是不是 迅雷又抽风了啊

### ISSUE THREAD

**Issue by budingniuzai** [fffonion/Xunlei-Fastdick#55]
还有就是我用新脚本生成的话会出错
File "swjsq.py", line 5
  <!DOCTYPE html>
 ^
SyntaxError:invalid syntax
不知道怎么回事    Python2.7 也重新安装了

**Comment by fffonion** [comment]
[重新下载](https://github.com/fffonion/Xunlei-Fastdick/raw/master/swjsq.py)
