### ISSUE TITLE
大神  运行脚本失败啊

### ISSUE THREAD

**Issue by budingniuzai** [fffonion/Xunlei-Fastdick#60]
安装好Python27 运行后出现
c:\python27> python swjsq.py &
  File "swjsq.py", line 5
     <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
怎么回事呢 下载的最新的swjsq.py

**Comment by fffonion** [comment]
[重新下载](https://github.com/fffonion/Xunlei-Fastdick/raw/master/swjsq.py)
