### ISSUE TITLE
PC上生成ipk时出错

### ISSUE THREAD

**Issue by pangys** [fffonion/Xunlei-Fastdick#61]
python 3.5.1，Win7 SP1 64bit，执行“python swjsq.py”后出现以下错误
> Warning: pycrypto not found, use pure-python implemention
Traceback (most recent call last):
  File "swjsq.py", line 559, in <module>
    fast_d1ck(uid, hashlib.md5(pwd).hexdigest(), TYPE_NORMAL_ACCOUNT)
  File "swjsq.py", line 260, in fast_d1ck
    dt, _payload = login_xunlei(uname, pwd, login_type)
  File "swjsq.py", line 176, in login_xunlei
    fake_device_id = hashlib.md5("%s23333" % pwd_md5).hexdigest() # just generate a 32bit string
TypeError: Unicode-objects must be encoded before hashing

**Comment by fffonion** [comment]
感谢汇报问题，请尝试 223719c
