### ISSUE TITLE
报错 Error 724: client request abnormal, blocked

### ISSUE THREAD

**Issue by asdf666** [fffonion/Xunlei-Fastdick#63]
- 所使用的版本：Python
- 运行的系统环境及版本：Windows 8.1 ，Python 2.7.11
- 产生错误的操作步骤：执行
- 运营商所在地：吉林长春

E:\My Documents\Desktop\Xunlei-Fastdick-master>swjsq.py
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: 吉林电信 Down 8M -> 10M, Up 8M -> 10M
Initializing upgrade
Error 724: client request abnormal, blocked

**Comment by fffonion** [comment]
用客户端没问题吧？

**Comment by asdf666** [comment]
试了PC版，没问题。手机客户端没试。
