### ISSUE TITLE
报错Error: clienttype null was Banned

### ISSUE THREAD

**Issue by Troyshen94** [fffonion/Xunlei-Fastdick#64]
按照教程http://www.nasyun.com/thread-25844-1-1.html
在黑群晖上用dock运行了您的Fastdick
但是日志提示：
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: 上海电信 Down 30M -&gt; 50M, Up 2M -&gt; 20M
Initializing upgrade
Error: clienttype null was Banned

不知该如何解决

**Comment by fffonion** [comment]
可以试下fffonion/Xunlei-Fastdick的docker镜像

**Comment by yswtrue** [comment]
貌似我docker pull fffonion/Xunlei-Fastdick说找不到源

**Comment by yswtrue** [comment]
可是我
docker pull fffonion/xunlei-fastdick
提示错误：
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/57/572a7bb97181a8c5af9e76bdf66baea20b77b62a9e986974e0cb3357e87cf81d/data?Expires=1466401792&Signature=ArBnGlbXybS5EnUzI80vEdx4yu43Cek6hihvRutMwXb9KrthyviVe22OXYbvSLqK0tnp-HuPk0g3uk-eNPLEYaWELmjt2iYqj~TS~Ku3VxSykbrm5WnHdD6Baeu22NLAZBJ3IJYqPfZx36Jm-jih8p~u5BMMYaJGvFFrlh7evtg_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout

**Comment by fffonion** [comment]
估计是墙的关系
群晖的docker能用第三方源不？可以的话试下index.alauda.cn/fffonion/xunlei-fastdick
