### ISSUE TITLE
IPK文件LUCI界面

### ISSUE THREAD

**Issue by lxhill** [fffonion/Xunlei-Fastdick#66]
请问大神能否制作成一个IPK文件，直接可以在LUCI里安装和操作？多谢多谢~

**Comment by fffonion** [comment]
你是说像[zz090923610/thunder-fastNiao](https://github.com/zz090923610/thunder-fastNiao)这样完全用bash实现的吗？
看有没有时间吧ww

**Comment by lxhill** [comment]
嗯，是的，坐等大神，多谢多谢！

**Comment by fffonion** [comment]
合并到#65
