### ISSUE TITLE
报错Error: get interface_ip failed

### ISSUE THREAD

**Issue by TingyiChen** [fffonion/Xunlei-Fastdick#68]
所使用的版本:Python
运行的系统环境及版本:Win10 1607,Python 3.5.2
包含错误信息的日志:
Warning: pycrypto not found, use pure-python implemention
Error: get interface_ip failed
产生错误的操作步骤:cmd执行python swjsq.py
运营商:湖北电信
打开http://api.portal.swjsq.vip.xunlei.com:81/v2/queryportal显示的内容如下
{"errno":520,"interface_port":"","interface_ip":"","province":"","sp":"","province_name":"","message":"ip check error:27.23.228.12 ret:-1","sp_name":""}

**Comment by fffonion** [comment]
改好了，shell版应该没有问题
我现在没测试环境，不造迅雷干了啥
![000](https://res.yooooo.us/e/haipa/haipa_01.jpg)

**Comment by timothyqiu** [comment]
在公司的网络下访问 queryportal 返回同样的 520 错误，手机快鸟显示「当前宽带不支持提速」。

可能是迅雷改在 queryportal 这一步就把不支持提速的条件判断了（非家庭宽带、不支持的地区或者运营商、设备线路先天无法提速……）

**Comment by timothyqiu** [comment]
额，算了，试了下家里的设备上也 520。

**Comment by TwoBall** [comment]
貌似湖北电信昨晚在做神马调整，然后我觉得这个锅并不该迅雷背。

**Comment by TingyiChen** [comment]
从昨天晚上开始这样，不知道在干嘛，湖北的ip段迅雷好像都没法识别

**Comment by TingyiChen** [comment]
@timothyqiu 我这电脑客户端正常，不过检测不出我签约的速度

**Comment by TingyiChen** [comment]
现在正常了。。。
