### ISSUE TITLE
openwart x86 & macosx 10.11 运行均报错 KeyError: 'can_upgrade'

### ISSUE THREAD

**Issue by chenjau** [fffonion/Xunlei-Fastdick#69]
报错的信息都是一样的.

Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
Traceback (most recent call last):
  File "./swjsq.py", line 568, in <module>
    fast_d1ck(uid, pwd_md5, TYPE_NUM_ACCOUNT, save = False)
  File "./swjsq.py", line 286, in fast_d1ck
    if not _['can_upgrade']:
KeyError: 'can_upgrade'

**Comment by fffonion** [comment]
运行下这个看屏幕输出什么？
[swjsq.zip](https://github.com/fffonion/Xunlei-Fastdick/files/425871/swjsq.zip)

**Comment by chenjau** [comment]
运行后除了2104650607, 2073591827这两个数字不一样外, 其他输出一样, 如下:

mac 输出:
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
{u'errno': 520, u'message': u'ip check error:2104650607', u'richmessage': u'\u5f53\u524d\u5bbd\u5e26\u4e0d\u652f\u6301\u63d0\u901f', u'timestamp': 1471578522, u'sequence': 0}
Traceback (most recent call last):
  File "swjsq.py", line 569, in <module>
    fast_d1ck(uid, pwd_md5, TYPE_NUM_ACCOUNT, save = False)
  File "swjsq.py", line 287, in fast_d1ck
    if not _['can_upgrade']:
KeyError: 'can_upgrade'


openwrt 输出:
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
{u'errno': 520, u'message': u'ip check error:2073591827', u'richmessage': u'\u5f53\u524d\u5bbd\u5e26\u4e0d\u652f\u6301\u63d0\u901f', u'timestamp': 1471578585, u'sequence': 0}
Traceback (most recent call last):
  File "swjsq.py", line 569, in <module>
    fast_d1ck(uid, pwd_md5, TYPE_NUM_ACCOUNT, save = False)
  File "swjsq.py", line 287, in fast_d1ck
    if not _['can_upgrade']:
KeyError: 'can_upgrade'

**Comment by fffonion** [comment]
这个提示是 当前宽带不支持提速，我等下改一下错误的判断条件。
建议你重新连一下宽带。
