### ISSUE TITLE
小米路由mini开发版2.5.7不再支持wget https安全连接，脚本无法运行

### ISSUE THREAD

**Issue by ninggu2008** [fffonion/Xunlei-FastDick#7]
最近迅雷快鸟官方的加速插件上架了，但是还没这个脚本好用，经常提速失效，需要进插件重新提速，其中每天早上7点必然失效。于是继续用脚本。
这次更新更新了busybox，wget有重大变化，wget的输出没了，没法提取连接信息了，wget也不能wget https安全连接了，导致直接没法连接迅雷加速服务器。
或许可以替换回上个版本的busybox，但是系统是read only的，据网上反馈，小米好像做了限制，重新mount也不能mount rw，或许把上个版本的busybox提取放到U盘运行？
又或许可以另外安装个wget，我这里opkg update卡住，好像连接不上源。而且小米限制修改系统，只能安装到U盘，到时候也会很麻烦。
总之先退回上个版本系统吧，反正这个版本还挺稳定。

**Comment by fffonion** [comment]
源里有curl不？改成curl -k --data "a=b" URL 也可以。
官方那个插件能提取出来不，参考一下
（难道做个lua版的0.0

**Comment by fffonion** [comment]
PS 其实登陆迅雷的那个url用http也能连 233

**Comment by ninggu2008** [comment]
用http能连？我把里面的部分改成 wget http://login.mobile.reg2t.sandai.net:80/，我这里显示：
--2015-08-21 19:26:03--  http://login.mobile.reg2t.sandai.net/
Resolving login.mobile.reg2t.sandai.net... 123.150.173.198
Connecting to login.mobile.reg2t.sandai.net|123.150.173.198|:80... failed: Connection refused.
拒绝连接。

路由固件有curl：
root@XiaoQiang:~# curl ?
curl: (3) <url> malformed

小米路由mini带的官方迅雷快鸟插件：
http://pan.baidu.com/s/1bnwg6Gf

**Comment by fffonion** [comment]
哦那大概我记错了-v- 试试curl支不支持https？
mips的汇编看都看不懂……
![20150821172252](https://cloud.githubusercontent.com/assets/2135445/9413347/526e0c56-486c-11e5-91d7-e6df18c5375c.jpg)

**Comment by ninggu2008** [comment]
非常感谢，换用curl，已经解决问题了。2.5.7固件curl也能用。
