### ISSUE TITLE
脚本运行一段时间后，不能自动重新登陆

### ISSUE THREAD

**Issue by DonisChan** [fffonion/Xunlei-Fastdick#70]
最近快鸟脚本运行几个钟左右，就不能加速，在迅雷安全中心查看登陆记录，差不多每10分钟登陆一次，过一段时间后就停止自动登陆，也停止了加速，需要重新启动脚本，维持时间不超过24小时，是不是迅雷修改了协议？麻烦大神 研究一下。

**Comment by fffonion** [comment]
是python版还是shell脚本，贴一下日志

**Comment by fffonion** [comment]
另外快鸟论坛反映浙江地区因为G20，加速有点问题

**Comment by DonisChan** [comment]
是路由器潘多拉的脚本，不好意思不知道在哪里看日志，系统、内核日志都没有swjsq的字段。我是在深圳的，前段时间都一直可以自动续命，出差2个月回来发现失效了，踢完了最新的swjsq脚本也还是这样。

**Comment by fffonion** [comment]
可以logread|grep swjsq看下

**Comment by DonisChan** [comment]
运行输出：
session is EC9B37D212936BFE2A9CA434D01AC706
{"bandwidth":{"downstream":50,"upstream":2},"dial_account":"szmcneys@163.gd","errno":0,"message":"","province":"guang_dong","province_name":"骞夸笢","richmessage":"","sequence":0,"sp":"tel","sp_name":"鐢典俊","timestamp":1471951733}

**Comment by fffonion** [comment]
这个看起来没问题啊 😄

**Comment by DonisChan** [comment]
我也觉得没问题，昨天晚上到今天加速都没有失效，不知道能保持多久哈哈哈。麻烦大神啦~

**Comment by fffonion** [comment]
好🌚

**Comment by qiumzh** [comment]
我觉得现在的加速是昙花一现，过一会就失效。都不知道哪里出的问题。
我用的是广州电信。
（ 小尾巴：https://blog.meduo.cc ）

**Comment by fffonion** [comment]
@qiumzh 可以尝试更改心跳时间，查找一下代码里的590，改成小一点的数值（单位是秒）
（贴的链接好像和这个项目没有关系，我删掉了）

**Comment by DonisChan** [comment]
大神，看下图片这两天又会失效了，15:22之后就不能续命了，而且登录的设备号最后两次的和之前的不一样，这个登录设备号和通过XshellPortable手动登录的一样，好奇怪。
![qq 20160829165148](https://cloud.githubusercontent.com/assets/19591953/18046156/21c5a348-6e09-11e6-90cf-050dcd8a327e.png)

**Comment by fffonion** [comment]
@DonisChan 通过XshellPortable手动登录是什么意思？

**Comment by DonisChan** [comment]
Xshell连接到路由器,输入(/bin/swjsq &)之后。就会提示这些：
session is *
{"bandwidth":{"downstream":50,"upstream":2},"dial_account":"*","errno":0,"message":"","province":"guang_dong","province_name":"骞夸笢","richmessage":"","sequence":0,"sp":"tel","sp_name":"鐢典俊","timestamp":1471951733}
然后就能够保持提速一段时间。

**Comment by DonisChan** [comment]
@fffonion  就是图里这样
![qq 20160829223730](https://cloud.githubusercontent.com/assets/19591953/18055153/4f5f59c2-6e39-11e6-99d4-7f9c29528492.png)

**Comment by fffonion** [comment]
@DonisChan 好的 那15:12之前的那些是同一路由器运行的？都是shell脚本版吗？

**Comment by DonisChan** [comment]
@fffonion 15：12，15：22都是路由器自动运行swjsq登陆的，但是这2个时间点的设备号却变了和前面的不一样，然后一直到我下班回家都没有再自动运行了，需要用shell脚本来登陆，用shell登陆的话，设备号就一定是e5ba0e14*不会变。晚上6点多用shell登陆了一次，大概9点钟就失效了，真是奇怪
![qq 20160829233020](https://cloud.githubusercontent.com/assets/19591953/18056957/a12a2dc0-6e40-11e6-919e-07053499e62f.png)

**Comment by fffonion** [comment]
登陆之后运行`ps|grep swjsq`看下是否有多个swjsq进程？

**Comment by DonisChan** [comment]
好像是的确有多个，怎么删啊？
![1](https://cloud.githubusercontent.com/assets/19591953/18057997/f240d46c-6e44-11e6-903e-ed8ce3feadd1.png)

**Comment by fffonion** [comment]
`kill -9 2662 10875 26335`
以后如果不想保持后台运行，登录ssh之后运行的时候最后不要加`&`，这样你关了shell它就会自己退出

**Comment by DonisChan** [comment]
好的谢谢。
