### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by jiuxiaxixi** [fffonion/Xunlei-Fastdick#72]
zxy@zxy-pc:~/Xunlei-Fastdick$ python swjsq.py 
Error: login failed, 您的帐号存在异常,请登录安全中心确认！
{u'isequenceNo': 1000001, u'errorCode': 6, u'cmdID': 2, u'errorIsRetry': 0, u'protocolVersion': 108, u'platformVersion': 1, u'errorDesc': u'\u60a8\u7684\u5e10\u53f7\u5b58\u5728\u5f02\u5e38,\u8bf7\u767b\u5f55\u5b89\u5168\u4e2d\u5fc3\u786e\u8ba4\uff01', u'sCompressed': 0, u'errorDescUrl': u'http://verify2.xunlei.com/image?t=MEA', u'verifyType': u'MEA'}

**Comment by jiuxiaxixi** [comment]
不知道怎么弄

**Comment by fffonion** [comment]
### 提示“您的帐号存在异常,请登录安全中心确认”的排查方法
1. 登陆迅雷下载客户端、迅雷快鸟客户端是否需要验证码？如果是且长期出现，请向迅雷客服反映。
2. 是否频繁多次启动脚本或同时启动了多个脚本？登录路由器使用`ps |grep swjsq`查看是否有多个进程

**Comment by viqbgrg** [comment]
你的解决了吗???我出现了和你一模一样的问题

**Comment by viqbgrg** [comment]
迅雷快鸟登陆并不需要验证码

**Comment by 4ft35t** [comment]
删除 .swjsq.account，再重新添加一个 swjsq.account.txt 就好了

**Comment by DeTeKe** [comment]
Error: login failed, 协议不合法，请联系客服确认！
{'protocolVersion': 108, 'errorIsRetry': 0, 'errorCode': 12, 'cmdID': 2, 'errorDescUrl': '', 'errorDesc': '协 议不合法，请联系客服确认！', 'isequenceNo': 1000001, 'platformVersion': 1, 'sCompressed': 0}

**Comment by fffonion** [comment]
合并 #97
