### ISSUE TITLE
运行一段时间，就发现停止加速了

### ISSUE THREAD

**Issue by huangegg33** [fffonion/Xunlei-Fastdick#73]
所使用的版本 (PC:Python 3.5)
运行的系统环境及版本 (PC 操作系统:win 10)
包含错误信息的日志(在下面)

 运营商所在地：广东电信

我先是在路由端使用的，接着发现出现问题了，会失效，我就在PC端运行swjsq.py测试
我把LOG贴上来吧
但我必须把程序关闭，再打开，才能有加速效果～
辛苦大大

23:12:36 {'dial_account': 'ADSL账号@163.gd', 'province': 'guang_dong', 'sequence': 0, 'sp_name': '电信', 'bandwidth': {'upstream': 2, 'downstream': 50}, 'richmessage': '', 'timestamp': 1473001963, 'errno': 0, 'province_name': '广东', 'sp': 'tel', 'message': ''}
23:22:27 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473002554, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
23:32:17 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473003144, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
23:42:07 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473003734, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
23:51:57 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473004325, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
00:01:48 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473004916, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
00:11:38 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473005507, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
00:21:28 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473006097, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
00:31:19 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473006687, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
00:41:09 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473007278, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
00:50:59 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473007868, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
01:00:50 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473008458, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
01:10:40 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473009048, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
01:20:30 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473009639, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
01:30:20 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473010229, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
01:40:11 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473010819, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
01:50:01 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473011409, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
01:59:51 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473012000, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
02:09:47 {'dial_account': 'ADSL账号@163.gd', 'province': 'guang_dong', 'sequence': 0, 'sp_name': '电信', 'bandwidth': {'upstream': 2, 'downstream': 50}, 'richmessage': '', 'timestamp': 1473012595, 'errno': 0, 'province_name': '广东', 'sp': 'tel', 'message': ''}
02:19:37 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473013186, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
02:29:28 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473013776, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
02:39:18 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473014366, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
02:49:08 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473014956, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
02:58:58 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473015547, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
03:08:49 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473016137, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}
03:18:39 {'sequence': 0, 'richmessage': '', 'upgrade_type': 1, 'peerid': '94DE80A52F63004V', 'errno': 0, 'userid': '49329295', 'timestamp': 1473016727, 'message': '', 'client_type': 'android-swjsq-2.0.3.4'}

**Comment by fffonion** [comment]
这个log似乎看不出哪里有问题
PC端开着swjsq.py的话加速会停止吗？

**Comment by supppig** [comment]
其实这个问题，我这里也出现过好多次。碰巧我也是广东电信的。。
这个问题，其实是由于发送心跳包的时候，由于路由上传下载过大（BT或者其他原因），导致心跳包超时。然后即使以后停止下载网络畅通后，再发送心跳包网络也不再加速了。
我不知道心跳包有没有一个反馈代码，再根据这个代码，判断加速是否继续生效，如果不生效，则重启脚本，行不行呢？

**Comment by fffonion** [comment]
如果能有log就知道了，现在只知道心跳的时候返回not exist channel需要重新登陆

**Comment by supppig** [comment]
@fffonion 那现在的脚本有这个检测到not exist channel，就重新登陆的功能么？由于上述的问题，我现在的做法是每隔1小时重启脚本，但不是长久之计啊~~~

**Comment by fffonion** [comment]
现在not exist
channel就会重新登陆，另外每三个小时会重新登陆。我记得漏跳一次心跳，下次心跳不会报错，但是已经不加速了。如果是超时的话倒是可以判断的

**Comment by supppig** [comment]
如果这样的话，那能不能加上心跳包超时后，直接重新登陆。
如果重新登陆也超时，那么10s后继续重新登陆，直到成功（因为要和BT下载抢速度，所以可能会继续超时）。

**Comment by huangegg33** [comment]
我就是路由上的LOG显示不详细，我换成PC测试了，也是会停止加速哦，但我并没有使用BT或迅雷等长时间抢占网速的软件，只是正常使用，但不久，就会发现加速已停止，只能靠手动关闭进程，再开启，才能有效，麻烦您了

**Comment by fffonion** [comment]
@huangegg33 如果没有心跳超时，我暂时没想到什么原因，你可以试试我贴的这个版本，把心跳从10分钟改成了5分钟
[swjsq.zip](https://github.com/fffonion/Xunlei-Fastdick/files/468685/swjsq.zip)

**Comment by huangegg33** [comment]
@fffonion 我测试了，貌似会出错，我贴上来给您看看，辛苦您了

LOG如下：
12:14:21 {'errno': 0, 'userid': '49329295', 'upgrade_type': 1, 'timestamp': 1473826463, 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'sequence': 0, 'peerid': '94DE80A52F63004V', 'message': ''}
12:19:12 {'errno': 0, 'userid': '49329295', 'upgrade_type': 1, 'timestamp': 1473826753, 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'sequence': 0, 'peerid': '94DE80A52F63004V', 'message': ''}
12:24:02 {'errno': 0, 'userid': '49329295', 'upgrade_type': 1, 'timestamp': 1473827043, 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'sequence': 0, 'peerid': '94DE80A52F63004V', 'message': ''}
12:28:52 {'errno': 0, 'userid': '49329295', 'upgrade_type': 1, 'timestamp': 1473827334, 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'sequence': 0, 'peerid': '94DE80A52F63004V', 'message': ''}
12:33:43 {'errno': 0, 'userid': '49329295', 'upgrade_type': 1, 'timestamp': 1473827624, 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'sequence': 0, 'peerid': '94DE80A52F63004V', 'message': ''}
12:38:33 {'errno': 0, 'userid': '49329295', 'upgrade_type': 1, 'timestamp': 1473827914, 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'sequence': 0, 'peerid': '94DE80A52F63004V', 'message': ''}
12:43:48 {'timestamp': 1473828229, 'dial_account': '宽带账号@163.gd', 'sequence': 0, 'sp': 'tel', 'sp_name': '电信', 'richmessage': '', 'errno': 0, 'province_name': '广东', 'message': '', 'bandwidth': {'upstream': 2, 'downstream': 50}, 'province': 'guang_dong'}
12:48:38 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473828519}
12:53:28 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473828809}
12:58:18 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473829100}
13:03:09 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473829390}
13:07:59 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473829680}
13:13:10 Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Program Files (x86)\Python35-32\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "C:\Program Files (x86)\Python35-32\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Program Files (x86)\Python35-32\lib\http\client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "C:\Program Files (x86)\Python35-32\lib\http\client.py", line 911, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Python35-32\lib\http\client.py", line 854, in send
    self.connect()
  File "C:\Program Files (x86)\Python35-32\lib\http\client.py", line 1229, in connect
    super().connect()
  File "C:\Program Files (x86)\Python35-32\lib\http\client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Program Files (x86)\Python35-32\lib\socket.py", line 711, in create_connection
    raise err
  File "C:\Program Files (x86)\Python35-32\lib\socket.py", line 702, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\huang\Desktop\kuainiao\swjsq.py", line 338, in fast_d1ck
    _dt_t, _paylod_t = renew_xunlei(dt['userID'], dt['sessionID'])
  File "C:\Users\huang\Desktop\kuainiao\swjsq.py", line 223, in renew_xunlei
    ct = http_req('https://login.mobile.reg2t.sandai.net:443/', body = _payload, headers = header_xl, encoding = 'gbk')
  File "C:\Users\huang\Desktop\kuainiao\swjsq.py", line 167, in http_req
    resp = urllib2.urlopen(req, data = body)
  File "C:\Program Files (x86)\Python35-32\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Python35-32\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "C:\Program Files (x86)\Python35-32\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "C:\Program Files (x86)\Python35-32\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python35-32\lib\urllib\request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Program Files (x86)\Python35-32\lib\urllib\request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>

13:18:00 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473830282}
13:22:51 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473830572}
13:27:41 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473830862}
13:32:31 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473831152}
13:37:21 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473831443}
13:42:12 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473831733}
13:47:02 {'peerid': '94DE80A52F63004V', 'sequence': 0, 'userid': '49329295', 'richmessage': '', 'client_type': 'android-swjsq-2.0.3.4', 'errno': 0, 'upgrade_type': 1, 'message': '', 'timestamp': 1473832023}

**Comment by fffonion** [comment]
这个错是没能迅雷的session续命，但是是被捕获住的，所以按道理是不影响加速。但从逻辑上说应该出错了要重复之前的步骤，总之我改一下

**Comment by fffonion** [comment]
新版地址 https://github.com/fffonion/Xunlei-Fastdick/raw/07cdeef45d385fecf02f1d9d39f82035fe04fd44/swjsq.py
这次我就不改心跳时间了。之前的发现加速已停止，有显示什么错误吗？

**Comment by Insenc** [comment]
我生成的swjsq_wget.sh有语法错误呀
第47行then前面少了个分号=。=

**Comment by fffonion** [comment]
手滑，已修改：）连不上家里的树莓派，暂时没法测试shell版了

**Comment by huangegg33** [comment]
@fffonion 我这边测试还是会停止加速，我先试试官方的软件，之后再向您说一下情况，我看看是否官方的问题，辛苦您了

**Comment by fffonion** [comment]
ok

**Comment by htfcuddles** [comment]
上海电信，同样一段时间后停止加速，查看stdout发现以下错误：
Error 717: account auth session failed result:402
Error 718: account auth session failed result:403

**Comment by sola97** [comment]
我这浙江的也不行，放路由器上第一个十分钟后就加速无效了，系统日志里正常renew xunlei,keepalive
PC上好点，20分钟左右才加速无效，log无异常
这时在官方客户端上都显示已提速的

**Comment by fffonion** [comment]
@sola97 客户端显示已提速的话说明脚本的逻辑应该是正常的，试一下用客户端会不会也有这种情况。还有关掉的issue都是已经解决了的，就不要回复了，可以开个新的

**Comment by tenhow** [comment]
这个是包装的swjsq，这是因为你的宽带重新拨号了，或者swjsq没有正常退出，所以没有重置宽带。解决方法是需要发送recover request，恢复原有带宽。

你可以下载swjsq在任意设备上，然后配置好帐号密码，运行后用ctl-c退出，以发送recover request。

**Comment by tenhow** [comment]
提供一个临时解决办法
目前我是在
```
        def _atexit_func():
            print("Sending recover request")
            try:
                self.api('recover', extras = "dial_account=%s" % _dial_account)
            except KeyboardInterrupt:
                print('Secondary ctrl+c pressed, exiting')
            try:
                logfd.close()
            except:
                pass
```
之前加入
```
      def recovery():
            print("recover request")
            self.api('recover', extras = "dial_account=%s" % _dial_account)
        recovery()
```
暂时这样执行，我没看f大的代码，这个位置是在发送提速前，所以有效。

**Comment by xxxyangyu** [comment]
> 你可以下载swjsq在任意设备上，然后配置好帐号密码，运行后用ctl-c退出，以发送recover request。

您好，我是在折腾路由器的时候不断重启，不断拨号，因此加速一直没有成功，一直返回的是812. 重新下载脚本并且执行了ctrl c 发送了reconver request。 但是还是加速失败 812错误。 这个要等多久ISP才会反应过来？

还有，因为经常折腾路由玩，这个加速功能就会经常处于812状态（原谅我忘记正确退出），因此有没有一个更好的方式来结束这种812的状态呢？
