### ISSUE TITLE
群晖docker里无法成功下载快鸟提示命令运行失败！

### ISSUE THREAD

**Issue by cloudflyz** [fffonion/Xunlei-Fastdick#77]
![docker](https://cloud.githubusercontent.com/assets/9921947/18701192/f4e4642e-800d-11e6-921e-0a8c30a77334.png)
怎么能解决？下载wordpress sh什么的都可以

**Comment by asaboss** [comment]
用ssh进群辉，然后用输入命令就可以了docker pull fffonion/Xunlei-Fastdick，主要还是群辉的BUG

**Comment by microstart** [comment]
su就没事了，群晖安全权限限制
