### ISSUE TITLE
发现路由器重启后，就不加速了

### ISSUE THREAD

**Issue by zjheric** [fffonion/Xunlei-Fastdick#78]
首次在群晖里用docker部署好以后，从30M加速到了50M。
然而当路由器重启后，加速就失效了。
尝试停止docker中的容器，重新打开后，显示如下：说是已经加速了，但是实测还是只有30M。
这时我用PC端的快鸟加速，也只能是30M，不知为何。请问有哪位知道解决方法么？
Warning: pycrypto not found, use pure-python implemention
stdout
11:36:41
Login xunlei succeeded
stdout
11:36:42
To Upgrade: 上海电信 Down 30M -&gt; 50M, Up 2M -&gt; 20M
stdout
11:36:42
Initializing upgrade
stdout
11:36:42
Error 812: speedup server already speed up
stdout
11:36:42
Already upgraded, continuing

**Comment by fffonion** [comment]
already upgraded是因为之前的加速状态没有退出，可以使用客户端或者python脚本停止加速后重新加速
