### ISSUE TITLE
padavan固件下生成的sh文件无法加速

### ISSUE THREAD

**Issue by yezz5** [fffonion/Xunlei-Fastdick#79]
Padavan固件下面输入账号、密码自动生成swjsq_wget.sh运行后不能提速
经对比发现一行代码有差异 peerid=20769331BB2D004V，而pc上运行生成的swjsq_wget.sh文件中peerid=0023247F9290004V，仅仅这个差异就导致无法运行，请问这一行代码是什么意思，修改上述代码之后就能正常运行。求解。

**Comment by fffonion** [comment]
peerid=mac地址004V
最近也有用户反应没法加速，可能是同一原因。
等我有测试环境了再看

**Comment by fffonion** [comment]
如果仍有问题请重新打开issue
