### ISSUE TITLE
能否开发一款不需要绑定宽带账号的程序

### ISSUE THREAD

**Issue by yezz5** [fffonion/Xunlei-Fastdick#80]
目前迅雷快鸟需要绑带在一个账号下，一个账号只能提速一条宽带，不能借用给别人提速。
找到一款功能相同的叫做光速大师的软件，问了客服得到的答复是不需要绑定宽带，同时它也有android版本，相信移植到openwrt平台应该也可以。如果有可能希望能做一个光速大师的openwrt版本。
附:光速大师网站链接
http://gs.xunyou.com
底下有android版本的下载地址。

**Comment by fffonion** [comment]
迅雷快鸟的工作原理不是由我决定的，建议去[快鸟论坛](http://bbs.xunlei.com/forum-183-1.html)反映
另外我想不会有产品能够同时加速多个ip，这样大家都用同一个账号就可以了233
