### ISSUE TITLE
The ssl and hashlib module might not be available on OpenWRT

### ISSUE THREAD

**Issue by timothyqiu** [fffonion/Xunlei-Fastdick#83]
Since SSL support is always provided by a separate package<sup>[1]</sup> from the base python installation on OpenWRT, the `ssl` module is optional. But the `ssl` module is imported directly without checking its existence<sup>[2]</sup>.

This is also true for the `hashlib` module which is provided with the `ssl` module on OpenWRT<sup>[1]</sup>.

[1]: https://wiki.openwrt.org/doc/software/python
[2]: https://github.com/fffonion/Xunlei-Fastdick/blob/03a3aaf2299caf6c99543d0c66038b4ed0634b58/swjsq.py#L11

**Comment by fffonion** [comment]
Thanks 😄
