### ISSUE TITLE
Python can not run

### ISSUE THREAD

**Issue by gyy443** [fffonion/Xunlei-Fastdick#86]
root@OpenWrt:/usr/bin# cd swjsq
root@OpenWrt:/usr/bin/swjsq# ls
swjsq.account.txt  swjsq.py
root@OpenWrt:/usr/bin/swjsq# python ./swjsq.py
  File "./swjsq.py", line 5
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
root@OpenWrt:/usr/bin/swjsq#

**Comment by fffonion** [comment]
你的swjsq.py可能有问题，请按照相关的教程重新下载试试
