### ISSUE TITLE
登陆成功却无法加速

### ISSUE THREAD

**Issue by sjx95** [fffonion/Xunlei-Fastdick#87]
我的运营商是支持迅雷快鸟提速的，之前在Win下面测试过了。
使用python脚本登陆时提示，登陆成功，但是加速失败。
我没找到详细日志，而且我也不懂python，来开个issue。

请问这是什么情况？日志在哪里？

Python 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC] on linux2
GNU bash，版本 4.4.5(1)-release (x86_64-suse-linux-gnu)
openSUSE Tumbleweed, kernel 4.9.0
山东电信

操作过程
$ python swjsq.py 
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
Error: can not upgrade, so sad TAT

**Comment by fffonion** [comment]
Error: can not
upgrade这个是快鸟api返回的，如果确认运营商支持提速，可以检查一下有没有系统代理或者iptables规则等可能影响出口ip的设置

**Comment by sjx95** [comment]
明白了，我的v4出口只有一个，所以应该不是出口的影响。
既然这个Error是API返回的，那应该是官方抽风了，thx。

ps 现在变成这个鬼样子了，不知道电信抽啥风。

python swjsq.py 
Warning: pycrypto not found, use pure-python implemention
Login xunlei succeeded
To Upgrade: 山东电信 Down 20M -> 100M, Up 2M -> 10M
Initializing upgrade
Error 812: speedup server already speed up
Already upgraded, continuing

**Comment by fffonion** [comment]
这个是之前已经加过速了，不影响的
