### ISSUE TITLE
很多错误

### ISSUE THREAD

**Issue by NIGHT-CORE** [fffonion/Xunlei-FastDick#9]
以py模式运行报错：UnicodeEncodeError: 'ascii' codec can't encode characters 
以ipk模式运行'报错':
Connecting to api.portal.swjsq.vip.xunlei.com:81 (61.155.183.136:81)
-                    100% |*****************************************************************************|   155   0:00:00 ETA
wget: not an http or ftp url: https://login.mobile.reg2t.sandai.net:443/
session is empty
uid is empty

是不是PY的版本一定要高于2.7.9+

**Comment by fffonion** [comment]
UnicodeEncodeError和系统的LANG以及LC_ALL有关，请设置成zh_CN.UTF-8
第二个问题是因为wget没有编译https支持，请使用curl版https://github.com/fffonion/Xunlei-FastDick/tree/MiWifi

**Comment by NIGHT-CORE** [comment]
谢谢，解答。

**Comment by fffonion** [comment]
@NIGHT-CORE 刚修改了一下，可以试下用没有解决问题：）
