### ISSUE TITLE
脚本被封了？

### ISSUE THREAD

**Issue by supppig** [fffonion/Xunlei-Fastdick#90]
X:\>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Error: login failed, 您的帐号存在异常,请登录安全中心确认！
{u'isequenceNo': 1000001, u'errorCode': 6, u'cmdID': 2, u'errorIsRetry': 0, u'protocolVersion': 108, u'platformVersion': 1, u'errorDesc': u'\u60a8\u7684\u5e10\u53f7\u5b58\u5728\u5f02\u5e38,\u8bf7\u767b\u5f55\u5b89\u5168\u4e2d\u5fc3\u786e\u8ba4\uff01', u'sCompressed': 0, u'errorDescUrl': u'http://verify2.xunlei.com/image?t=MEA', u'verifyType': u'MEA'}

坐标广州电信。重启路由光猫无效。
以上是win上运行python程序，在路由上运行python是同样提示的。
路由上的sh运行也是差不多这个提示（该sh以前一直成功），提示session is empty，然后echo $ret，结果也是这句话。
在win下运行迅雷官方的客户端，提速成功。
登陆迅雷安全中心，未见异常。

**Comment by supppig** [comment]
刚再测试了一次，又OK了。暂时判定为迅雷快鸟抽风吧。。。
X:\>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Warning: you are probably not xunlei vip, buy buy buy!
[Debug] isVip:0 payId:0 payName:[u'----']
Login xunlei succeeded
To Upgrade: 广东电信 Down 20M -> 50M, Up 0M -> 0M
Initializing upgrade
Error 812: speedup server already speed up
Already upgraded, continuing

**Comment by fffonion** [comment]
脚本用的是手机版的登录地址，所以和pc版应该互不影响。
如果下次爆炸了我看下能不能撸新的手机版登录

**Comment by cokebar** [comment]
应该是迅雷升级了安全策略 非常用地点登录会警告 去安全中心修改以下常用地点即可

**Comment by cokebar** [comment]
应该是某种检测机制 导致迅雷认为账号存在风险 让输入验证码 返回的那个url就是验证码的地址
@fffonion 针对这种情况可以加一个手动输入验证码的功能。

**Comment by fffonion** [comment]
@cokebar 有道理，我看下

**Comment by cokebar** [comment]
@supppig 从迅雷安全中心的记录看 我的出现这种情况应该是登录地点的问题 安全中心里设置的常用地点和现在的地点不同 我改到现在的地点以后 等了12小时后再登录就正常了

**Comment by yezz5** [comment]
520再次喷到这个问题，提示协议不支持，换同一账号下面的数字id进行登录，提示 您的帐号存在异常,请登录安全中心确认，返回值是验证码，没有输入验证码的地方，难受。望解答

**Comment by cokebar** [comment]
只能等一段时间 24小时以后再登录
脚本能输入验证码就好了

**Comment by cokebar** [comment]
不过验证码是图片 命令行下如何显示？

**Comment by fffonion** [comment]
可以考虑做一个调用浏览器打开验证码的功能，欢迎发pr

**Comment by vexetron** [comment]
期待验证码支持。
