### ISSUE TITLE
是不是换协议了

### ISSUE THREAD

**Issue by ljk4160** [fffonion/Xunlei-Fastdick#91]
Error: login failed, 协议不合法，请联系客服确认！
{u'isequenceNo': 1000001, u'errorCode': 12, u'cmdID': 2, u'errorIsRetry': 0, u'protocolVersion': 108, u'platformVersion': 1, u'errorDesc': u'\u534f\u8bae\u4e0d\u5408\u6cd5\uff0c\u8bf7\u8054\u7cfb\u5ba2\u670d\u786e\u8ba4\uff01', u'sCompressed': 0, u'errorDescUrl': u''}

**Comment by fffonion** [comment]
合并 #97
