### ISSUE TITLE
用脚本导致帐号被封了？

### ISSUE THREAD

**Issue by supppig** [fffonion/Xunlei-Fastdick#93]
一直用路由的脚本。直到这2天，突然发现用不了了。各种排查。。。
PC能登陆，手机不能登陆（登陆无效，12DeviceID无效）。
换一个无会员的帐号测试，手机能登陆成功！

用PC测试python脚本。
X:\>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Error: login failed, 协议不合法，请联系客服确认！
{u'isequenceNo': 1000001, u'errorCode': 12, u'cmdID': 2, u'errorIsRetry': 0, u'protocolVersion': 108, u'platformVersion': 1, u'errorDesc': u'\u534f\u8bae\u4e0d\u5408\u6cd5\uff0c\u8bf7\u8054\u7cfb\u5ba2\u670d\u786e\u8ba4\uff01', u'sCompressed': 0, u'errorDescUrl': u''}

测试那个无会员的帐号：
X:\>python swjsq.py
Warning: pycrypto not found, use pure-python implemention
Warning: you are probably not xunlei vip, buy buy buy!
[Debug] isVip:0 payId:0 payName:[u'----']
Login xunlei succeeded
To Upgrade: 广东电信 Down 20M -> 50M, Up 0M -> 0M
Initializing upgrade
Error 518: qurey vip response user not has business property

看来帐号出问题了！！！不过安全中心没任何提示！！
我找客服去了。。。

**Comment by supppig** [comment]
刚才问了客服，客服说登陆太频繁了。。。我等2小时后再试试。。

**Comment by yezz5** [comment]
可以了吗？我也是碰到这个问题，提示都一样，我等了半天还是登不上，前两天才充值的18个月会员。最可怕的是我的账号绑定的手机停用了，现在都无法修改密码。持续关注中！

**Comment by supppig** [comment]
我现在OK了，一觉醒来，就好了。对了，如果你用老毛子固件的，记得把迅雷快鸟的插件关了。然后ssh上路由，把 ps | grep "Fast" 的进程全部终结（固件貌似有bug，会进程残留，导致一直登陆）。如果不会的话，就把开关关了，然后重启路由。

**Comment by fffonion** [comment]
合并 #97
