### ISSUE TITLE
上行加速报错

### ISSUE THREAD

**Issue by Coolkids** [fffonion/Xunlei-Fastdick#96]
python版本2.6
系统LEDE,内核4.9.31

Error: can not upgrade, so sad TAT tel_proxy resp max_bands_down less than bands_down

我这区域只支持上行加速不支持下行加速
所以直接去检查下行加速的api会异常

上行加速的API地址是:http://api.upportal.swjsq.vip.xunlei.com/v2/queryportal

**Comment by fffonion** [comment]
merge #98
