### ISSUE TITLE
感谢作者，下行加速完美，上行没办法加速。。。

### ISSUE THREAD

**Issue by xyl94k** [fffonion/Xunlei-Fastdick#98]
感谢作者，下行加速完美，上行没办法加速，求帮忙解决一下

**Comment by fffonion** [comment]
能贴个充值上行加速会员的链接不，没有可以测试的账号
![qq 20170714025220](https://user-images.githubusercontent.com/2135445/28194966-8d7c53d2-6815-11e7-96f3-abce49204169.jpg)

**Comment by xyl94k** [comment]
哇，我很想提供我账号，但是迅雷账号绑定了宽带号。。。。。
http://act.vip.xunlei.com/vip/2016/ssts/
这是上行提速的，现在快鸟客户端也集成了这个的

**Comment by fffonion** [comment]
嗯上面木有充值的地方，所以现在没法开上行加速会员了吗

**Comment by xyl94k** [comment]
直接下载这个客户端或者快鸟，里面就有上行加速，试用时长用完他就会提醒你充值，就在右边。。。

**Comment by fffonion** [comment]
哦看到了，谢谢
![8h c 55dva0 zzoib d 6tj](https://user-images.githubusercontent.com/2135445/28195835-bc4c6fda-681a-11e7-8fe9-502b0a44093b.jpg)

**Comment by linran125** [comment]
同求上行啊，其实插件的上行加速有时还能生效一会，但绝大多数时间都是无效状态，具体有什么规律还没摸清

**Comment by fffonion** [comment]
上行的接口和下行一毛一样，改个url就行。我看一下怎么判断用户有没有开上行或者加速的会员，就可以发布了

**Comment by spr007** [comment]
大神什么时候能更新呀

**Comment by linran125** [comment]
期待新版发布呀

**Comment by fffonion** [comment]
添加了py版的上行加速，生成的shell脚本暂时没动，稍后再加

**Comment by linran125** [comment]
测试ok！非常感谢！！

**Comment by linran125** [comment]
`10:56:19 Login xunlei succeeded
10:56:19 Expire date for fastdick: 20171024
10:56:20 Expire date for upstream acceleration: 20171024
10:56:20 To Upgrade: 黑龙江电信 down 100M -> 200M, up 4M -> 10M
10:56:20 Initializing upgrade
10:56:22 Upgrade done: down 200M, up 30M
`
最后一句显示up 30M，但是实际只有10M

**Comment by fffonion** [comment]
@linran125 30M是迅雷返回的，我这里也有这个问题，但是下行加速里显示的上行速度反而是对的
